package vistas;

import comercio.ControllerSingleton;
import controladoresJPA.MarcaJpaController;
import controladoresJPA.exceptions.NonexistentEntityException;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.Marca;
import vistas.modelos.MarcaTableModel;

/**
 *
 * @author Mauro Federico Lopez
 */
public class AdministrarMarcasUI extends javax.swing.JPanel {

    private MarcaJpaController marcaJpaController;
    private MarcaTableModel marcaTableModel;

    /**
     * Creates new form AdministrarMarcasUI
     */
    public AdministrarMarcasUI() {
        initComponents();
        marcaJpaController = ControllerSingleton.getMarcaJpaController();
        marcaTableModel = new MarcaTableModel();
        tablaMarcas.setModel(marcaTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nuevaMarcaUI = new javax.swing.JDialog();
        etiquetaNombre = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        campoAbreviacion = new javax.swing.JTextField();
        etiquetaAbreviacion = new javax.swing.JLabel();
        botonGuardarNuevaMarca = new javax.swing.JButton();
        jsp = new javax.swing.JScrollPane();
        tablaMarcas = new javax.swing.JTable();
        panelBotones = new javax.swing.JPanel();
        botonAgregarMarca = new javax.swing.JButton();
        botonEliminarMarca = new javax.swing.JButton();

        nuevaMarcaUI.setTitle("Nueva marca");
        nuevaMarcaUI.setMinimumSize(new java.awt.Dimension(245, 97));

        etiquetaNombre.setText("Nombre");

        etiquetaAbreviacion.setText("Abreviación");

        botonGuardarNuevaMarca.setText("Agregar Nueva Marca");
        botonGuardarNuevaMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarNuevaMarcaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nuevaMarcaUILayout = new javax.swing.GroupLayout(nuevaMarcaUI.getContentPane());
        nuevaMarcaUI.getContentPane().setLayout(nuevaMarcaUILayout);
        nuevaMarcaUILayout.setHorizontalGroup(
            nuevaMarcaUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevaMarcaUILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nuevaMarcaUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(nuevaMarcaUILayout.createSequentialGroup()
                        .addGroup(nuevaMarcaUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(etiquetaAbreviacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(etiquetaNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(nuevaMarcaUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(campoAbreviacion)))
                    .addComponent(botonGuardarNuevaMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nuevaMarcaUILayout.setVerticalGroup(
            nuevaMarcaUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevaMarcaUILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nuevaMarcaUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaNombre)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nuevaMarcaUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaAbreviacion)
                    .addComponent(campoAbreviacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonGuardarNuevaMarca)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Administrar Marcas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        setMaximumSize(new java.awt.Dimension(900, 500));
        setMinimumSize(new java.awt.Dimension(900, 500));
        setPreferredSize(new java.awt.Dimension(900, 500));
        setLayout(new java.awt.BorderLayout());

        tablaMarcas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaMarcas.getTableHeader().setReorderingAllowed(false);
        jsp.setViewportView(tablaMarcas);

        add(jsp, java.awt.BorderLayout.CENTER);

        panelBotones.setMaximumSize(new java.awt.Dimension(900, 33));
        panelBotones.setMinimumSize(new java.awt.Dimension(900, 33));
        panelBotones.setPreferredSize(new java.awt.Dimension(900, 33));

        botonAgregarMarca.setText("Agregar Nueva Marca");
        botonAgregarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarMarcaActionPerformed(evt);
            }
        });
        panelBotones.add(botonAgregarMarca);

        botonEliminarMarca.setText("Eliminar Marca");
        botonEliminarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarMarcaActionPerformed(evt);
            }
        });
        panelBotones.add(botonEliminarMarca);

        add(panelBotones, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarNuevaMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarNuevaMarcaActionPerformed
        Marca nuevaMarca = new Marca();
        nuevaMarca.setNombre(campoNombre.getText());
        nuevaMarca.setAbreviacion(campoAbreviacion.getText());
        marcaJpaController.crearMarca(nuevaMarca);
        limpiarCampos();
        nuevaMarcaUI.setVisible(false);
    }//GEN-LAST:event_botonGuardarNuevaMarcaActionPerformed

    private void botonEliminarMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarMarcaActionPerformed
        try {
            Integer rowSelected = tablaMarcas.getSelectedRow();
            if (rowSelected >= 0)
                marcaJpaController.destruirMarca(marcaTableModel.obtenerMarca(rowSelected).getId());
        } catch (NonexistentEntityException ex) {
            Logger.getLogger(AdministrarMarcasUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonEliminarMarcaActionPerformed

    private void botonAgregarMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarMarcaActionPerformed
        nuevaMarcaUI.setVisible(true);
        nuevaMarcaUI.pack();
    }//GEN-LAST:event_botonAgregarMarcaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarMarca;
    private javax.swing.JButton botonEliminarMarca;
    private javax.swing.JButton botonGuardarNuevaMarca;
    private javax.swing.JTextField campoAbreviacion;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JLabel etiquetaAbreviacion;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JScrollPane jsp;
    private javax.swing.JDialog nuevaMarcaUI;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JTable tablaMarcas;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {
        campoNombre.setText("");
        campoAbreviacion.setText("");
    }

}
