package vistas;

import java.awt.BorderLayout;
import javax.swing.JComponent;

/**
 *
 * @author Mauro Federico Lopez
 */
public class AdministradorUI extends javax.swing.JFrame {

    /**
     * Creates new form AdministradorUI
     */
    public AdministradorUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraMenu = new javax.swing.JMenuBar();
        menuAdministrar = new javax.swing.JMenu();
        itemMenuAdministrarEmpleados = new javax.swing.JMenuItem();
        itemMenuAdministrarSucursales = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador");
        setMaximumSize(new java.awt.Dimension(900, 500));
        setMinimumSize(new java.awt.Dimension(900, 500));
        setPreferredSize(new java.awt.Dimension(900, 500));

        menuAdministrar.setText("Administrar");

        itemMenuAdministrarEmpleados.setText("Adm empleados");
        itemMenuAdministrarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuAdministrarEmpleadosActionPerformed(evt);
            }
        });
        menuAdministrar.add(itemMenuAdministrarEmpleados);

        itemMenuAdministrarSucursales.setText("Adm sucursales");
        itemMenuAdministrarSucursales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuAdministrarSucursalesActionPerformed(evt);
            }
        });
        menuAdministrar.add(itemMenuAdministrarSucursales);

        jMenuItem1.setText("jMenuItem1");
        menuAdministrar.add(jMenuItem1);

        barraMenu.add(menuAdministrar);

        setJMenuBar(barraMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemMenuAdministrarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuAdministrarEmpleadosActionPerformed
        agregarComponenteAlCentro(new AdministrarEmpleadosUI());
    }//GEN-LAST:event_itemMenuAdministrarEmpleadosActionPerformed

    private void itemMenuAdministrarSucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuAdministrarSucursalesActionPerformed
        agregarComponenteAlCentro(new AdministrarSucursalesUI());
    }//GEN-LAST:event_itemMenuAdministrarSucursalesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministradorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministradorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministradorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministradorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new AdministradorUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem itemMenuAdministrarEmpleados;
    private javax.swing.JMenuItem itemMenuAdministrarSucursales;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menuAdministrar;
    // End of variables declaration//GEN-END:variables

    private void agregarComponenteAlCentro(JComponent componente) {
        getContentPane().removeAll();
        add(componente, BorderLayout.CENTER);
        componente.setVisible(true);
        componente.updateUI();
        pack();
    }
}
