package vistas;

import comercio.ControllerSingleton;
import controladoresJPA.EmpleadoJpaController;
import controladoresJPA.exceptions.NonexistentEntityException;
import javax.swing.JOptionPane;
import modelo.*;
import vistas.modelos.GerenteTableModel;
import vistas.modelos.GestorInventarioTableModel;
import vistas.modelos.VendedorTableModel;

/**
 *
 * @author Mauro Federico Lopez
 */
public class AdministrarEmpleadosUI extends javax.swing.JPanel {

    private GerenteTableModel gerenteTableModel;
    private GestorInventarioTableModel gestorInventarioTableModel;
    private VendedorTableModel vendedorTableModel;
    private EmpleadoJpaController empleadoJpaController;
    private Tipoempleado tipoempleado;

    /**
     * Creates new form AdministrarEmpleadosUI
     */
    public AdministrarEmpleadosUI() {
        initComponents();
        empleadoJpaController = ControllerSingleton.getEmpleadoJpaController();
        gerenteTableModel = new GerenteTableModel();
        tablaGerentes.setModel(gerenteTableModel);
        gestorInventarioTableModel = new GestorInventarioTableModel();
        tablaGestoresDeInventario.setModel(gestorInventarioTableModel);
        vendedorTableModel = new VendedorTableModel();
        tablaVendedores.setModel(vendedorTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nuevoEmpleadoUI = new javax.swing.JDialog();
        etiquetaApellido = new javax.swing.JLabel();
        campoApellido = new javax.swing.JTextField();
        etiquetaNombre = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        etiquetaUsername = new javax.swing.JLabel();
        campoUsername = new javax.swing.JTextField();
        etiquetaPassword = new javax.swing.JLabel();
        etiquetaSucursal = new javax.swing.JLabel();
        campoSucursal = new javax.swing.JComboBox();
        etiquetaAlmacen = new javax.swing.JLabel();
        campoAlmacen = new javax.swing.JComboBox();
        etiquetaPuntoDeVenta = new javax.swing.JLabel();
        campoPuntoDeVenta = new javax.swing.JComboBox();
        botonGuardarGerente = new javax.swing.JButton();
        campoPassword = new javax.swing.JPasswordField();
        panelGerentes = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        botonNuevoGerente = new javax.swing.JButton();
        botonEliminarGerente = new javax.swing.JButton();
        jspTablaGerentes = new javax.swing.JScrollPane();
        tablaGerentes = new javax.swing.JTable();
        panelGestoresDeInventario = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        botonNuevoGestorDeInventario = new javax.swing.JButton();
        botonEliminarGestorDeInventario = new javax.swing.JButton();
        jspTablaGestoresDeInventario = new javax.swing.JScrollPane();
        tablaGestoresDeInventario = new javax.swing.JTable();
        panelVendedores = new javax.swing.JPanel();
        jspTablaVendedores = new javax.swing.JScrollPane();
        tablaVendedores = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        botonNuevoVendedor = new javax.swing.JButton();
        botonEliminarVendedor = new javax.swing.JButton();

        nuevoEmpleadoUI.setTitle("Nuevo Gerente");
        nuevoEmpleadoUI.setLocationByPlatform(true);
        nuevoEmpleadoUI.setResizable(false);

        etiquetaApellido.setText("Apellido");

        etiquetaNombre.setText("Nombre");

        etiquetaUsername.setText("Nombre de usuario");

        etiquetaPassword.setText("Contraseña");

        etiquetaSucursal.setText("Seleccione sucursal");

        campoSucursal.setModel(new vistas.modelos.SucursalComboBoxModel());

        etiquetaAlmacen.setText("Seleccione almacén");

        campoAlmacen.setModel(new vistas.modelos.AlmacenComboBoxModel());

        etiquetaPuntoDeVenta.setText("Seleccione punto de venta");

        campoPuntoDeVenta.setModel(new vistas.modelos.PuntoDeVentaComboBoxModel());

        botonGuardarGerente.setText("Guardar");
        botonGuardarGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarGerenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nuevoEmpleadoUILayout = new javax.swing.GroupLayout(nuevoEmpleadoUI.getContentPane());
        nuevoEmpleadoUI.getContentPane().setLayout(nuevoEmpleadoUILayout);
        nuevoEmpleadoUILayout.setHorizontalGroup(
            nuevoEmpleadoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevoEmpleadoUILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nuevoEmpleadoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(etiquetaSucursal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaAlmacen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaPuntoDeVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nuevoEmpleadoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoApellido)
                    .addComponent(campoNombre)
                    .addComponent(campoUsername)
                    .addComponent(campoSucursal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonGuardarGerente, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(campoAlmacen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoPuntoDeVenta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoPassword))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nuevoEmpleadoUILayout.setVerticalGroup(
            nuevoEmpleadoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevoEmpleadoUILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nuevoEmpleadoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaApellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nuevoEmpleadoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nuevoEmpleadoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nuevoEmpleadoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaPassword)
                    .addComponent(campoPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nuevoEmpleadoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaSucursal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nuevoEmpleadoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaAlmacen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nuevoEmpleadoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoPuntoDeVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaPuntoDeVenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonGuardarGerente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Administrar empleados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        setMaximumSize(new java.awt.Dimension(900, 500));
        setMinimumSize(new java.awt.Dimension(900, 500));
        setLayout(new java.awt.BorderLayout());

        panelGerentes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gerentes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        panelGerentes.setMaximumSize(new java.awt.Dimension(900, 150));
        panelGerentes.setMinimumSize(new java.awt.Dimension(900, 150));
        panelGerentes.setPreferredSize(new java.awt.Dimension(900, 150));
        panelGerentes.setLayout(new java.awt.BorderLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(100, 32767));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 140));

        botonNuevoGerente.setText("Nuevo");
        botonNuevoGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoGerenteActionPerformed(evt);
            }
        });

        botonEliminarGerente.setText("Eliminar");
        botonEliminarGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarGerenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonEliminarGerente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonNuevoGerente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonNuevoGerente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonEliminarGerente)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        panelGerentes.add(jPanel1, java.awt.BorderLayout.LINE_START);

        jspTablaGerentes.setMaximumSize(new java.awt.Dimension(450, 32767));
        jspTablaGerentes.setMinimumSize(new java.awt.Dimension(450, 23));
        jspTablaGerentes.setPreferredSize(new java.awt.Dimension(450, 402));

        tablaGerentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaGerentes.getTableHeader().setReorderingAllowed(false);
        jspTablaGerentes.setViewportView(tablaGerentes);

        panelGerentes.add(jspTablaGerentes, java.awt.BorderLayout.CENTER);

        add(panelGerentes, java.awt.BorderLayout.PAGE_START);

        panelGestoresDeInventario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestores de inventario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        panelGestoresDeInventario.setMaximumSize(new java.awt.Dimension(900, 150));
        panelGestoresDeInventario.setMinimumSize(new java.awt.Dimension(100, 150));
        panelGestoresDeInventario.setPreferredSize(new java.awt.Dimension(900, 150));
        panelGestoresDeInventario.setLayout(new java.awt.BorderLayout());

        jPanel2.setMaximumSize(new java.awt.Dimension(100, 32767));
        jPanel2.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 200));

        botonNuevoGestorDeInventario.setText("Nuevo");
        botonNuevoGestorDeInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoGestorDeInventarioActionPerformed(evt);
            }
        });

        botonEliminarGestorDeInventario.setText("Eliminar");
        botonEliminarGestorDeInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarGestorDeInventarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonNuevoGestorDeInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonEliminarGestorDeInventario, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonNuevoGestorDeInventario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonEliminarGestorDeInventario)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        panelGestoresDeInventario.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jspTablaGestoresDeInventario.setMaximumSize(new java.awt.Dimension(450, 32767));
        jspTablaGestoresDeInventario.setMinimumSize(new java.awt.Dimension(450, 23));
        jspTablaGestoresDeInventario.setPreferredSize(new java.awt.Dimension(450, 402));

        tablaGestoresDeInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaGestoresDeInventario.getTableHeader().setReorderingAllowed(false);
        jspTablaGestoresDeInventario.setViewportView(tablaGestoresDeInventario);

        panelGestoresDeInventario.add(jspTablaGestoresDeInventario, java.awt.BorderLayout.CENTER);

        add(panelGestoresDeInventario, java.awt.BorderLayout.CENTER);

        panelVendedores.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vendedores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        panelVendedores.setMaximumSize(new java.awt.Dimension(900, 150));
        panelVendedores.setMinimumSize(new java.awt.Dimension(900, 150));
        panelVendedores.setPreferredSize(new java.awt.Dimension(900, 150));
        panelVendedores.setLayout(new java.awt.BorderLayout());

        jspTablaVendedores.setMaximumSize(new java.awt.Dimension(450, 32767));
        jspTablaVendedores.setMinimumSize(new java.awt.Dimension(450, 23));
        jspTablaVendedores.setPreferredSize(new java.awt.Dimension(450, 402));

        tablaVendedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaVendedores.getTableHeader().setReorderingAllowed(false);
        jspTablaVendedores.setViewportView(tablaVendedores);

        panelVendedores.add(jspTablaVendedores, java.awt.BorderLayout.CENTER);

        jPanel3.setMaximumSize(new java.awt.Dimension(100, 32767));
        jPanel3.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 166));

        botonNuevoVendedor.setText("Nuevo");
        botonNuevoVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoVendedorActionPerformed(evt);
            }
        });

        botonEliminarVendedor.setText("Eliminar");
        botonEliminarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarVendedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonNuevoVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonEliminarVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonNuevoVendedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonEliminarVendedor)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        panelVendedores.add(jPanel3, java.awt.BorderLayout.LINE_START);

        add(panelVendedores, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarGerenteActionPerformed
        try {
            camposNuevoGerenteCompletos();
            String apellido = campoApellido.getText();
            String nombre = campoNombre.getText();
            String username = campoUsername.getText();
            String password = campoPassword.getText();

            if(tipoempleado == Tipoempleado.GERENTE) {
                Sucursal sucursal = (Sucursal) campoSucursal.getSelectedItem();
                empleadoJpaController.registrarNuevoGerente(apellido, nombre, username, password, sucursal);
            } else {
                if(tipoempleado == Tipoempleado.GESTOR) {
                    Almacen almacen = (Almacen) campoAlmacen.getSelectedItem();
                    empleadoJpaController.registrarNuevoGestorDeInventario(apellido, nombre, username, password, almacen);
                } else {
                    if(tipoempleado == Tipoempleado.VENDEDOR) {
                        PuntoVenta puntoDeVenta = (PuntoVenta) campoPuntoDeVenta.getSelectedItem();
                        empleadoJpaController.registrarNuevoVendedor(apellido, nombre, username, password, puntoDeVenta);
                    }
                }
            }

            nuevoEmpleadoUI.setVisible(false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
         }
    }//GEN-LAST:event_botonGuardarGerenteActionPerformed

    private void botonNuevoGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoGerenteActionPerformed
        limpiarCampos();
        tipoempleado = Tipoempleado.GERENTE;
        etiquetaSucursal.setVisible(true);
        campoSucursal.setVisible(true);
        etiquetaAlmacen.setVisible(false);
        campoAlmacen.setVisible(false);
        etiquetaPuntoDeVenta.setVisible(false);
        campoPuntoDeVenta.setVisible(false);
        nuevoEmpleadoUI.setVisible(true);
        nuevoEmpleadoUI.pack();
    }//GEN-LAST:event_botonNuevoGerenteActionPerformed

    private void botonNuevoGestorDeInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoGestorDeInventarioActionPerformed
        limpiarCampos();
        tipoempleado = Tipoempleado.GESTOR;
        etiquetaSucursal.setVisible(false);
        campoSucursal.setVisible(false);
        etiquetaAlmacen.setVisible(true);
        campoAlmacen.setVisible(true);
        etiquetaPuntoDeVenta.setVisible(false);
        campoPuntoDeVenta.setVisible(false);
        nuevoEmpleadoUI.setVisible(true);
        nuevoEmpleadoUI.pack();
    }//GEN-LAST:event_botonNuevoGestorDeInventarioActionPerformed

    private void botonNuevoVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoVendedorActionPerformed
        limpiarCampos();
        tipoempleado = Tipoempleado.VENDEDOR;
        etiquetaSucursal.setVisible(false);
        campoSucursal.setVisible(false);
        etiquetaAlmacen.setVisible(false);
        campoAlmacen.setVisible(false);
        etiquetaPuntoDeVenta.setVisible(true);
        campoPuntoDeVenta.setVisible(true);
        nuevoEmpleadoUI.setVisible(true);
        nuevoEmpleadoUI.pack();
    }//GEN-LAST:event_botonNuevoVendedorActionPerformed

    private void botonEliminarGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarGerenteActionPerformed
        try {
            Integer filaSeleccionada = tablaGerentes.getSelectedRow();
            Gerente gerente = gerenteTableModel.obtenerGerente(filaSeleccionada);
            empleadoJpaController.eliminarGerente(gerente);
        } catch (NonexistentEntityException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonEliminarGerenteActionPerformed

    private void botonEliminarGestorDeInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarGestorDeInventarioActionPerformed
        try {
            Integer filaSeleccionada = tablaGestoresDeInventario.getSelectedRow();
            GestorInventario gestorDeInventario = gestorInventarioTableModel.obtenerGestorDeInventario(filaSeleccionada);
            empleadoJpaController.eliminarGestorDeInventario(gestorDeInventario);
        } catch (NonexistentEntityException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonEliminarGestorDeInventarioActionPerformed

    private void botonEliminarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarVendedorActionPerformed
        try {
            Integer filaSeleccionada = tablaVendedores.getSelectedRow();
            Vendedor vendedor = vendedorTableModel.obtenerVendedor(filaSeleccionada);
            empleadoJpaController.eliminarVendedor(vendedor);
        } catch (NonexistentEntityException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonEliminarVendedorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEliminarGerente;
    private javax.swing.JButton botonEliminarGestorDeInventario;
    private javax.swing.JButton botonEliminarVendedor;
    private javax.swing.JButton botonGuardarGerente;
    private javax.swing.JButton botonNuevoGerente;
    private javax.swing.JButton botonNuevoGestorDeInventario;
    private javax.swing.JButton botonNuevoVendedor;
    private javax.swing.JComboBox campoAlmacen;
    private javax.swing.JTextField campoApellido;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JPasswordField campoPassword;
    private javax.swing.JComboBox campoPuntoDeVenta;
    private javax.swing.JComboBox campoSucursal;
    private javax.swing.JTextField campoUsername;
    private javax.swing.JLabel etiquetaAlmacen;
    private javax.swing.JLabel etiquetaApellido;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaPassword;
    private javax.swing.JLabel etiquetaPuntoDeVenta;
    private javax.swing.JLabel etiquetaSucursal;
    private javax.swing.JLabel etiquetaUsername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jspTablaGerentes;
    private javax.swing.JScrollPane jspTablaGestoresDeInventario;
    private javax.swing.JScrollPane jspTablaVendedores;
    private javax.swing.JDialog nuevoEmpleadoUI;
    private javax.swing.JPanel panelGerentes;
    private javax.swing.JPanel panelGestoresDeInventario;
    private javax.swing.JPanel panelVendedores;
    private javax.swing.JTable tablaGerentes;
    private javax.swing.JTable tablaGestoresDeInventario;
    private javax.swing.JTable tablaVendedores;
    // End of variables declaration//GEN-END:variables

    private void camposNuevoGerenteCompletos() throws Exception {
        if(campoApellido.getText().isEmpty())
            throw new Exception("No ha indicado el apellido del nuevo gerente.");
        if(campoNombre.getText().isEmpty())
            throw new Exception("No ha indicado el nombre del nuevo gerente.");
        if(campoUsername.getText().isEmpty())
            throw new Exception("No ha indicado el nombre de usuario del nuevo gerente.");
        if(campoPassword.getText().isEmpty())
            throw new Exception("No ha indicado la contraseña del nuevo gerente.");
    }

    private void limpiarCampos() {
        campoApellido.setText("");
        campoNombre.setText("");
        campoUsername.setText("");
        campoPassword.setText("");
        campoSucursal.setSelectedItem(null);
        campoAlmacen.setSelectedItem(null);
        campoPuntoDeVenta.setSelectedItem(null);
    }
}

enum Tipoempleado {
    GERENTE, GESTOR, VENDEDOR
}
