package vistas;

import comercio.ControllerSingleton;
import controladoresJPA.ProductoJpaController;
import controladoresJPA.exceptions.CampoIncompletoException;
import controladoresJPA.exceptions.CodigoProductoNoDisponibleException;
import controladoresJPA.exceptions.NonexistentEntityException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;
import modelo.*;
import vistas.modelos.*;

/**
 *
 * @author Mauro Federico Lopez
 */
public class AdministrarProductosUI extends javax.swing.JPanel {

    private ProductoJpaController productoJpaController;
    private ProductoTableModel productoTableModel;
    private Producto producto;

    /**
     * Creates new form AdministrarProductosUI
     */
    public AdministrarProductosUI() {
        initComponents();
        productoJpaController = ControllerSingleton.getProductoJpaController();
        productoTableModel = (ProductoTableModel) tablaProductos.getModel();
        campoPrecioNuevo.setValue(0);
        producto = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nuevoProductoUI = new javax.swing.JDialog();
        etiquetaCodigoNuevo = new javax.swing.JLabel();
        campoCodigoNuevo = new javax.swing.JTextField();
        campoDescripcionNuevo = new javax.swing.JTextField();
        etiquetaDescripcionNuevo = new javax.swing.JLabel();
        etiquetaPrecioNuevo = new javax.swing.JLabel();
        campoPrecioNuevo = new javax.swing.JFormattedTextField();
        etiquetaMarcaNuevo = new javax.swing.JLabel();
        campoMarcaNuevo = new javax.swing.JComboBox();
        etiquetaOrigenNuevo = new javax.swing.JLabel();
        campoOrigenNuevo = new javax.swing.JComboBox();
        etiquetaUnidadNuevo = new javax.swing.JLabel();
        campoUnidadNuevo = new javax.swing.JComboBox();
        etiquetaCategoriaNuevo = new javax.swing.JLabel();
        campoCategoriaNuevo = new javax.swing.JComboBox();
        botonGuardarNuevo = new javax.swing.JButton();
        botonCancelarNuevo = new javax.swing.JButton();
        editarProductoUI = new javax.swing.JDialog();
        etiquetaCodigoEditar = new javax.swing.JLabel();
        campoCodigoEditar = new javax.swing.JTextField();
        etiquetaDescripcionEditar = new javax.swing.JLabel();
        campoDescripcionEditar = new javax.swing.JTextField();
        etiquetaPrecioEditar = new javax.swing.JLabel();
        campoPrecioEditar = new javax.swing.JFormattedTextField();
        etiquetaMarcaEditar = new javax.swing.JLabel();
        campoMarcaEditar = new javax.swing.JComboBox();
        etiquetaOrigenEditar = new javax.swing.JLabel();
        campoOrigenEditar = new javax.swing.JComboBox();
        etiquetaUnidadEditar = new javax.swing.JLabel();
        campoUnidadEditar = new javax.swing.JComboBox();
        etiquetaCategoriaEditar = new javax.swing.JLabel();
        campoCategoriaEditar = new javax.swing.JComboBox();
        botonGuardarEditar = new javax.swing.JButton();
        botonCancelarEdicion = new javax.swing.JButton();
        jsp = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        panelBotones = new javax.swing.JPanel();
        botonNuevoProducto = new javax.swing.JButton();
        botonEliminarProducto = new javax.swing.JButton();
        botonEditarProducto = new javax.swing.JButton();

        nuevoProductoUI.setTitle("Nuevo Producto");
        nuevoProductoUI.setMinimumSize(new java.awt.Dimension(241, 227));
        nuevoProductoUI.setResizable(false);

        etiquetaCodigoNuevo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        etiquetaCodigoNuevo.setText("Código");

        etiquetaDescripcionNuevo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        etiquetaDescripcionNuevo.setText("Descripción");

        etiquetaPrecioNuevo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        etiquetaPrecioNuevo.setText("Precio unitario");

        campoPrecioNuevo.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat())));

        etiquetaMarcaNuevo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        etiquetaMarcaNuevo.setText("Marca");

        campoMarcaNuevo.setModel(new MarcaComboBoxModel());

        etiquetaOrigenNuevo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        etiquetaOrigenNuevo.setText("Origen");

        campoOrigenNuevo.setModel(new OrigenComboBoxModel());

        etiquetaUnidadNuevo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        etiquetaUnidadNuevo.setText("Unidad");

        campoUnidadNuevo.setModel(new UnidadComboBoxModel());

        etiquetaCategoriaNuevo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        etiquetaCategoriaNuevo.setText("Categoría");

        campoCategoriaNuevo.setModel(new CategoriaComboBoxModel());

        botonGuardarNuevo.setText("Guardar");
        botonGuardarNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarNuevoActionPerformed(evt);
            }
        });

        botonCancelarNuevo.setText("Cancelar");
        botonCancelarNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nuevoProductoUILayout = new javax.swing.GroupLayout(nuevoProductoUI.getContentPane());
        nuevoProductoUI.getContentPane().setLayout(nuevoProductoUILayout);
        nuevoProductoUILayout.setHorizontalGroup(
            nuevoProductoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevoProductoUILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nuevoProductoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nuevoProductoUILayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonGuardarNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonCancelarNuevo)
                        .addGap(41, 41, 41))
                    .addGroup(nuevoProductoUILayout.createSequentialGroup()
                        .addGroup(nuevoProductoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(nuevoProductoUILayout.createSequentialGroup()
                                .addGroup(nuevoProductoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(etiquetaCodigoNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(etiquetaDescripcionNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                                .addGap(10, 10, 10)
                                .addGroup(nuevoProductoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoDescripcionNuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoCodigoNuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(nuevoProductoUILayout.createSequentialGroup()
                                .addGroup(nuevoProductoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(etiquetaCategoriaNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                    .addComponent(etiquetaUnidadNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(etiquetaOrigenNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(nuevoProductoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoOrigenNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(nuevoProductoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(campoPrecioNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(campoMarcaNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(campoUnidadNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoCategoriaNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(nuevoProductoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(etiquetaMarcaNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(etiquetaPrecioNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(14, Short.MAX_VALUE))))
        );
        nuevoProductoUILayout.setVerticalGroup(
            nuevoProductoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevoProductoUILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nuevoProductoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCodigoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaCodigoNuevo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nuevoProductoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaDescripcionNuevo)
                    .addComponent(campoDescripcionNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nuevoProductoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaPrecioNuevo)
                    .addComponent(campoPrecioNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nuevoProductoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaMarcaNuevo)
                    .addComponent(campoMarcaNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nuevoProductoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaOrigenNuevo)
                    .addComponent(campoOrigenNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nuevoProductoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaUnidadNuevo)
                    .addComponent(campoUnidadNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nuevoProductoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaCategoriaNuevo)
                    .addComponent(campoCategoriaNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nuevoProductoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGuardarNuevo)
                    .addComponent(botonCancelarNuevo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        editarProductoUI.setTitle("Editar Producto");

        etiquetaCodigoEditar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        etiquetaCodigoEditar.setText("Código");

        etiquetaDescripcionEditar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        etiquetaDescripcionEditar.setText("Descripción");

        etiquetaPrecioEditar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        etiquetaPrecioEditar.setText("Precio unitario");

        campoPrecioEditar.setEditable(false);
        campoPrecioEditar.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat())));

        etiquetaMarcaEditar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        etiquetaMarcaEditar.setText("Marca");

        campoMarcaEditar.setModel(new MarcaComboBoxModel());

        etiquetaOrigenEditar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        etiquetaOrigenEditar.setText("Origen");

        campoOrigenEditar.setModel(new OrigenComboBoxModel());

        etiquetaUnidadEditar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        etiquetaUnidadEditar.setText("Unidad");

        campoUnidadEditar.setModel(new UnidadComboBoxModel());

        etiquetaCategoriaEditar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        etiquetaCategoriaEditar.setText("Categoría");

        campoCategoriaEditar.setModel(new CategoriaComboBoxModel());

        botonGuardarEditar.setText("Guardar");
        botonGuardarEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarEditarActionPerformed(evt);
            }
        });

        botonCancelarEdicion.setText("Cancelar");
        botonCancelarEdicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarEdicionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editarProductoUILayout = new javax.swing.GroupLayout(editarProductoUI.getContentPane());
        editarProductoUI.getContentPane().setLayout(editarProductoUILayout);
        editarProductoUILayout.setHorizontalGroup(
            editarProductoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editarProductoUILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editarProductoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editarProductoUILayout.createSequentialGroup()
                        .addGroup(editarProductoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(etiquetaDescripcionEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(etiquetaCodigoEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(4, 4, 4)
                        .addGroup(editarProductoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoDescripcionEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoCodigoEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(editarProductoUILayout.createSequentialGroup()
                        .addGroup(editarProductoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editarProductoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(etiquetaUnidadEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(etiquetaOrigenEditar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(etiquetaMarcaEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(etiquetaCategoriaEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                            .addComponent(etiquetaPrecioEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editarProductoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoOrigenEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(editarProductoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(campoPrecioEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(campoMarcaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(campoUnidadEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoCategoriaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(editarProductoUILayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(botonGuardarEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCancelarEdicion)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        editarProductoUILayout.setVerticalGroup(
            editarProductoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editarProductoUILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editarProductoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCodigoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaCodigoEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editarProductoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaDescripcionEditar)
                    .addComponent(campoDescripcionEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editarProductoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaPrecioEditar)
                    .addComponent(campoPrecioEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editarProductoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaMarcaEditar)
                    .addComponent(campoMarcaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editarProductoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaOrigenEditar)
                    .addComponent(campoOrigenEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editarProductoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaUnidadEditar)
                    .addComponent(campoUnidadEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editarProductoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaCategoriaEditar)
                    .addComponent(campoCategoriaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editarProductoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGuardarEditar)
                    .addComponent(botonCancelarEdicion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Administrar Productos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        setMaximumSize(new java.awt.Dimension(900, 500));
        setMinimumSize(new java.awt.Dimension(900, 500));
        setPreferredSize(new java.awt.Dimension(900, 500));
        setLayout(new java.awt.BorderLayout());

        tablaProductos.setModel(new ProductoTableModel());
        tablaProductos.getTableHeader().setReorderingAllowed(false);
        jsp.setViewportView(tablaProductos);

        add(jsp, java.awt.BorderLayout.CENTER);

        panelBotones.setMaximumSize(new java.awt.Dimension(900, 33));
        panelBotones.setMinimumSize(new java.awt.Dimension(900, 33));
        panelBotones.setPreferredSize(new java.awt.Dimension(900, 33));

        botonNuevoProducto.setText("Nuevo Producto");
        botonNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoProductoActionPerformed(evt);
            }
        });
        panelBotones.add(botonNuevoProducto);

        botonEliminarProducto.setText("Eliminar Producto");
        botonEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarProductoActionPerformed(evt);
            }
        });
        panelBotones.add(botonEliminarProducto);

        botonEditarProducto.setText("Editar Producto");
        botonEditarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarProductoActionPerformed(evt);
            }
        });
        panelBotones.add(botonEditarProducto);

        add(panelBotones, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void botonNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoProductoActionPerformed
        nuevoProductoUI.setVisible(true);
        nuevoProductoUI.pack();
    }//GEN-LAST:event_botonNuevoProductoActionPerformed

    private void botonEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarProductoActionPerformed
        try {
            int indice = tablaProductos.getSelectedRow();
            if (indice >= 0) {
                producto = productoTableModel.obtenerProducto(indice);
                productoJpaController.destruirProducto(producto.getId());
            } else
                throw new Exception("No ha seleccionado ningún producto.");
        } catch (NonexistentEntityException ex) {
            JOptionPane.showMessageDialog(null, "El producto seleccionado no pudo ser eliminado.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonEliminarProductoActionPerformed

    private void botonGuardarNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarNuevoActionPerformed
        try {
            camposDeNuevoProductoCompletos();
            Producto nuevoProducto = new Producto();
            nuevoProducto.setCodigo(campoCodigoNuevo.getText());
            nuevoProducto.setDescripcion(campoDescripcionNuevo.getText());
            nuevoProducto.setCategoria((Categoria) campoCategoriaNuevo.getSelectedItem());
            nuevoProducto.setMarca((Marca) campoMarcaNuevo.getSelectedItem());
            nuevoProducto.setUnidad((Unidad) campoUnidadNuevo.getSelectedItem());
            nuevoProducto.setOrigen((Origen) campoOrigenNuevo.getSelectedItem());
            nuevoProducto.setPrecioActual(((Number) campoPrecioNuevo.getValue()).doubleValue());
            productoJpaController.registrarProducto(nuevoProducto);
            limpiarCampos();
            nuevoProductoUI.setVisible(false);
        } catch(CampoIncompletoException ex) {
            ex.mostrarDialogo();
        } catch (CodigoProductoNoDisponibleException ex) {
            ex.mostrarDialogoDeError();
        } catch (Exception ex) {
            Logger.getLogger(AdministrarProductosUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonGuardarNuevoActionPerformed

    private void botonCancelarNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarNuevoActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_botonCancelarNuevoActionPerformed

    private void botonEditarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarProductoActionPerformed
        try {
            int indice = tablaProductos.getSelectedRow();
            if (indice >= 0) {
                producto = productoTableModel.obtenerProducto(indice);
                campoCodigoEditar.setText(producto.getCodigo());
                campoDescripcionEditar.setText(producto.getDescripcion());
                campoPrecioEditar.setValue(producto.getPrecioActual());
                campoMarcaEditar.setSelectedItem(producto.getMarca());
                campoOrigenEditar.setSelectedItem(producto.getOrigen());
                campoUnidadEditar.setSelectedItem(producto.getUnidad());
                campoCategoriaEditar.setSelectedItem(producto.getCategoria());
                editarProductoUI.setVisible(true);
                editarProductoUI.pack();
            } else
                throw new Exception("No ha seleccionado ningún producto.");
        } catch(CampoIncompletoException ex) {
            ex.mostrarDialogo();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonEditarProductoActionPerformed

    private void botonGuardarEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarEditarActionPerformed
        try {
            camposDeEdicionProductoCompletos();
            producto.setCodigo(campoCodigoEditar.getText());
            producto.setDescripcion(campoDescripcionEditar.getText());
            producto.setMarca((Marca) campoMarcaEditar.getSelectedItem());
            producto.setOrigen((Origen) campoOrigenEditar.getSelectedItem());
            producto.setUnidad((Unidad) campoUnidadEditar.getSelectedItem());
            producto.setCategoria((Categoria) campoCategoriaEditar.getSelectedItem());
            productoJpaController.editarProducto(producto);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonGuardarEditarActionPerformed

    private void botonCancelarEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarEdicionActionPerformed
        limpiarCamposEdicion();
        editarProductoUI.setVisible(false);
    }//GEN-LAST:event_botonCancelarEdicionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelarEdicion;
    private javax.swing.JButton botonCancelarNuevo;
    private javax.swing.JButton botonEditarProducto;
    private javax.swing.JButton botonEliminarProducto;
    private javax.swing.JButton botonGuardarEditar;
    private javax.swing.JButton botonGuardarNuevo;
    private javax.swing.JButton botonNuevoProducto;
    private javax.swing.JComboBox campoCategoriaEditar;
    private javax.swing.JComboBox campoCategoriaNuevo;
    private javax.swing.JTextField campoCodigoEditar;
    private javax.swing.JTextField campoCodigoNuevo;
    private javax.swing.JTextField campoDescripcionEditar;
    private javax.swing.JTextField campoDescripcionNuevo;
    private javax.swing.JComboBox campoMarcaEditar;
    private javax.swing.JComboBox campoMarcaNuevo;
    private javax.swing.JComboBox campoOrigenEditar;
    private javax.swing.JComboBox campoOrigenNuevo;
    private javax.swing.JFormattedTextField campoPrecioEditar;
    private javax.swing.JFormattedTextField campoPrecioNuevo;
    private javax.swing.JComboBox campoUnidadEditar;
    private javax.swing.JComboBox campoUnidadNuevo;
    private javax.swing.JDialog editarProductoUI;
    private javax.swing.JLabel etiquetaCategoriaEditar;
    private javax.swing.JLabel etiquetaCategoriaNuevo;
    private javax.swing.JLabel etiquetaCodigoEditar;
    private javax.swing.JLabel etiquetaCodigoNuevo;
    private javax.swing.JLabel etiquetaDescripcionEditar;
    private javax.swing.JLabel etiquetaDescripcionNuevo;
    private javax.swing.JLabel etiquetaMarcaEditar;
    private javax.swing.JLabel etiquetaMarcaNuevo;
    private javax.swing.JLabel etiquetaOrigenEditar;
    private javax.swing.JLabel etiquetaOrigenNuevo;
    private javax.swing.JLabel etiquetaPrecioEditar;
    private javax.swing.JLabel etiquetaPrecioNuevo;
    private javax.swing.JLabel etiquetaUnidadEditar;
    private javax.swing.JLabel etiquetaUnidadNuevo;
    private javax.swing.JScrollPane jsp;
    private javax.swing.JDialog nuevoProductoUI;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JTable tablaProductos;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {
        campoCodigoNuevo.setText("");
        campoDescripcionNuevo.setText("");
        campoPrecioNuevo.setValue(0);
        campoMarcaNuevo.setSelectedItem(null);
        campoMarcaNuevo.updateUI();
        campoOrigenNuevo.setSelectedItem(null);
        campoOrigenNuevo.updateUI();
        campoUnidadNuevo.setSelectedItem(null);
        campoUnidadNuevo.updateUI();
        campoCategoriaNuevo.setSelectedItem(null);
        campoCategoriaNuevo.updateUI();
    }

    private void limpiarCamposEdicion() {
        campoCodigoEditar.setText("");
        campoDescripcionEditar.setText("");
        campoPrecioEditar.setValue(0);
        campoMarcaEditar.setSelectedItem(null);
        campoMarcaEditar.updateUI();
        campoOrigenEditar.setSelectedItem(null);
        campoOrigenEditar.updateUI();
        campoUnidadEditar.setSelectedItem(null);
        campoUnidadEditar.updateUI();
        campoCategoriaEditar.setSelectedItem(null);
        campoCategoriaEditar.updateUI();
    }

    private void camposDeNuevoProductoCompletos() throws CampoIncompletoException {
        if(campoCodigoNuevo.getText().isEmpty())
            throw new CampoIncompletoException("No ha indicado un código.");
        if(campoDescripcionNuevo.getText().isEmpty())
            throw new CampoIncompletoException("No ha indicado una descripción.");
        if(campoPrecioNuevo.getText().isEmpty())
            throw new CampoIncompletoException("No ha indicado el precio del producto.");
        if(campoMarcaNuevo.getSelectedItem() == null)
            throw new CampoIncompletoException("No ha seleccionado una marca.");
        if(campoOrigenNuevo.getSelectedItem() == null)
            throw new CampoIncompletoException("No ha seleccionado un origen.");
        if(campoUnidadNuevo.getSelectedItem() == null)
            throw new CampoIncompletoException("No ha seleccionado una unidad.");
        if(campoCategoriaNuevo.getSelectedItem() == null)
            throw new CampoIncompletoException("No ha seleccionado una categoría.");
    }

    private void camposDeEdicionProductoCompletos() throws CampoIncompletoException {
        if(campoCodigoEditar.getText().isEmpty())
            throw new CampoIncompletoException("No ha indicado un código.");
        if(campoDescripcionEditar.getText().isEmpty())
            throw new CampoIncompletoException("No ha indicado una descripción.");
        if(campoMarcaEditar.getSelectedItem() == null)
            throw new CampoIncompletoException("No ha seleccionado una marca.");
        if(campoOrigenEditar.getSelectedItem() == null)
            throw new CampoIncompletoException("No ha seleccionado un origen.");
        if(campoUnidadEditar.getSelectedItem() == null)
            throw new CampoIncompletoException("No ha seleccionado una unidad.");
        if(campoCategoriaEditar.getSelectedItem() == null)
            throw new CampoIncompletoException("No ha seleccionado una categoría.");
    }
}
