package vistas;

import comercio.ControllerSingleton;
import controladoresJPA.AlmacenJpaController;
import controladoresJPA.PuntoVentaJpaController;
import controladoresJPA.exceptions.CodigoProductoNoRegistradoException;
import modelo.Almacen;
import modelo.PuntoVenta;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mauro Federico Lopez
 */
public class CorregirInventarioUI extends javax.swing.JPanel {

    private AlmacenJpaController almacenJpaController;
    private PuntoVentaJpaController puntoDeVentaJpaController;

    /**
     * Creates new form CorregirInventarioUI
     */
    public CorregirInventarioUI() {
        initComponents();
        almacenJpaController = ControllerSingleton.getAlmacenJpaController();
        puntoDeVentaJpaController = ControllerSingleton.getPuntoVentaJpaController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCorregirInventarioPuntoDeVenta = new javax.swing.JPanel();
        etiquetaPuntoDeVenta = new javax.swing.JLabel();
        campoPuntoDeVenta = new javax.swing.JComboBox();
        etiquetaCodigoProducto = new javax.swing.JLabel();
        campoCodigoProducto = new javax.swing.JTextField();
        etiquetaCantidadProducto = new javax.swing.JLabel();
        campoCantidadProducto = new javax.swing.JFormattedTextField();
        botonCorregirInventarioPuntoDeVenta = new javax.swing.JButton();
        panelCorregirInventarioAlmacen = new javax.swing.JPanel();
        etiquetaAlmacen = new javax.swing.JLabel();
        campoAlmacen = new javax.swing.JComboBox();
        etiquetaCodigoLote = new javax.swing.JLabel();
        campoCodigoLote = new javax.swing.JTextField();
        etiquetaCantidadLote = new javax.swing.JLabel();
        campoCantidadLote = new javax.swing.JFormattedTextField();
        botonCorregirInventarioAlmacen = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(900, 500));
        setMinimumSize(new java.awt.Dimension(900, 500));
        setLayout(new java.awt.BorderLayout());

        panelCorregirInventarioPuntoDeVenta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Corregir Inventario de Punto de Venta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        panelCorregirInventarioPuntoDeVenta.setMaximumSize(new java.awt.Dimension(900, 250));
        panelCorregirInventarioPuntoDeVenta.setMinimumSize(new java.awt.Dimension(900, 250));
        panelCorregirInventarioPuntoDeVenta.setPreferredSize(new java.awt.Dimension(900, 250));

        etiquetaPuntoDeVenta.setText("Seleccione un punto de venta");

        campoPuntoDeVenta.setModel(new vistas.modelos.PuntoDeVentaComboBoxModel());

        etiquetaCodigoProducto.setText("Ingrese el código de producto");

        etiquetaCantidadProducto.setText("Ingrese nueva cantidad");

        campoCantidadProducto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));

        botonCorregirInventarioPuntoDeVenta.setText("Corregir Inventario");
        botonCorregirInventarioPuntoDeVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCorregirInventarioPuntoDeVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCorregirInventarioPuntoDeVentaLayout = new javax.swing.GroupLayout(panelCorregirInventarioPuntoDeVenta);
        panelCorregirInventarioPuntoDeVenta.setLayout(panelCorregirInventarioPuntoDeVentaLayout);
        panelCorregirInventarioPuntoDeVentaLayout.setHorizontalGroup(
            panelCorregirInventarioPuntoDeVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCorregirInventarioPuntoDeVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCorregirInventarioPuntoDeVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etiquetaCantidadProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaCodigoProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaPuntoDeVenta, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCorregirInventarioPuntoDeVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCorregirInventarioPuntoDeVentaLayout.createSequentialGroup()
                        .addGroup(panelCorregirInventarioPuntoDeVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCorregirInventarioPuntoDeVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(campoPuntoDeVenta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(campoCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(campoCantidadProducto))
                        .addGap(66, 66, 66))
                    .addGroup(panelCorregirInventarioPuntoDeVentaLayout.createSequentialGroup()
                        .addComponent(botonCorregirInventarioPuntoDeVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(471, 471, 471))
        );
        panelCorregirInventarioPuntoDeVentaLayout.setVerticalGroup(
            panelCorregirInventarioPuntoDeVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCorregirInventarioPuntoDeVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCorregirInventarioPuntoDeVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoPuntoDeVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaPuntoDeVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCorregirInventarioPuntoDeVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(campoCodigoProducto)
                    .addComponent(etiquetaCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCorregirInventarioPuntoDeVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaCantidadProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCorregirInventarioPuntoDeVenta)
                .addGap(115, 115, 115))
        );

        add(panelCorregirInventarioPuntoDeVenta, java.awt.BorderLayout.PAGE_START);

        panelCorregirInventarioAlmacen.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Corregir Inventario de Almacén", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        etiquetaAlmacen.setText("Seleccione un almacén");

        campoAlmacen.setModel(new vistas.modelos.AlmacenComboBoxModel());

        etiquetaCodigoLote.setText("Ingrese el código de lote");

        etiquetaCantidadLote.setText("Ingrese nueva cantidad");

        campoCantidadLote.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));

        botonCorregirInventarioAlmacen.setText("Corregir Inventario");
        botonCorregirInventarioAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCorregirInventarioAlmacenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCorregirInventarioAlmacenLayout = new javax.swing.GroupLayout(panelCorregirInventarioAlmacen);
        panelCorregirInventarioAlmacen.setLayout(panelCorregirInventarioAlmacenLayout);
        panelCorregirInventarioAlmacenLayout.setHorizontalGroup(
            panelCorregirInventarioAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCorregirInventarioAlmacenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCorregirInventarioAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etiquetaAlmacen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaCodigoLote, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(etiquetaCantidadLote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCorregirInventarioAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoCantidadLote)
                    .addComponent(campoCodigoLote)
                    .addComponent(campoAlmacen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonCorregirInventarioAlmacen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                .addContainerGap(538, Short.MAX_VALUE))
        );
        panelCorregirInventarioAlmacenLayout.setVerticalGroup(
            panelCorregirInventarioAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCorregirInventarioAlmacenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCorregirInventarioAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCorregirInventarioAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(campoCodigoLote)
                    .addComponent(etiquetaCodigoLote, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCorregirInventarioAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCantidadLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaCantidadLote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCorregirInventarioAlmacen)
                .addGap(115, 115, 115))
        );

        add(panelCorregirInventarioAlmacen, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void botonCorregirInventarioPuntoDeVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCorregirInventarioPuntoDeVentaActionPerformed
        try {
            PuntoVenta puntoDeVenta = (PuntoVenta) campoPuntoDeVenta.getSelectedItem();
            String codigoProducto = campoCodigoProducto.getText();
            Double cantidad = ((Number) campoCantidadProducto.getValue()).doubleValue();
            puntoDeVentaJpaController.corregirProductoEnVenta(puntoDeVenta, codigoProducto, cantidad);
        } catch (CodigoProductoNoRegistradoException ex) {
            ex.mostrarDialogo();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonCorregirInventarioPuntoDeVentaActionPerformed

    private void botonCorregirInventarioAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCorregirInventarioAlmacenActionPerformed
        try {
            Almacen almacen = (Almacen) campoAlmacen.getSelectedItem();
            String codigoLote = campoCodigoLote.getText();
            Double cantidad = ((Number) campoCantidadLote.getValue()).doubleValue();
            almacenJpaController.corregirLoteAlmacenado(almacen, codigoLote, cantidad);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonCorregirInventarioAlmacenActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCorregirInventarioAlmacen;
    private javax.swing.JButton botonCorregirInventarioPuntoDeVenta;
    private javax.swing.JComboBox campoAlmacen;
    private javax.swing.JFormattedTextField campoCantidadLote;
    private javax.swing.JFormattedTextField campoCantidadProducto;
    private javax.swing.JTextField campoCodigoLote;
    private javax.swing.JTextField campoCodigoProducto;
    private javax.swing.JComboBox campoPuntoDeVenta;
    private javax.swing.JLabel etiquetaAlmacen;
    private javax.swing.JLabel etiquetaCantidadLote;
    private javax.swing.JLabel etiquetaCantidadProducto;
    private javax.swing.JLabel etiquetaCodigoLote;
    private javax.swing.JLabel etiquetaCodigoProducto;
    private javax.swing.JLabel etiquetaPuntoDeVenta;
    private javax.swing.JPanel panelCorregirInventarioAlmacen;
    private javax.swing.JPanel panelCorregirInventarioPuntoDeVenta;
    // End of variables declaration//GEN-END:variables
}
