package vistas;

import java.awt.BorderLayout;
import javax.swing.JComponent;

/**
 *
 * @author Mauro Federico Lopez
 */
public class GestionGerenciaUI extends javax.swing.JFrame {

    /**
     * Creates new form GestionGerenciaUI
     */
    public GestionGerenciaUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraDeMenu = new javax.swing.JMenuBar();
        menuOperaciones = new javax.swing.JMenu();
        itemMenuModificarPrecioPorPorcentaje = new javax.swing.JMenuItem();
        itemMenuCrearOfertaTemporal = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        itemMenuVentasMensual = new javax.swing.JMenuItem();
        itemMenuVentaPorCategoria = new javax.swing.JMenuItem();
        itemMenuVentaPorMarca = new javax.swing.JMenuItem();
        itemMenuEgresoProductos = new javax.swing.JMenuItem();
        itemMenuVariacionPrecios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion Gerencia");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(950, 550));
        setResizable(false);

        menuOperaciones.setText("Operaciones");

        itemMenuModificarPrecioPorPorcentaje.setText("Modificar precio por porcentaje");
        itemMenuModificarPrecioPorPorcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuModificarPrecioPorPorcentajeActionPerformed(evt);
            }
        });
        menuOperaciones.add(itemMenuModificarPrecioPorPorcentaje);

        itemMenuCrearOfertaTemporal.setText("Crear una oferta temporal");
        itemMenuCrearOfertaTemporal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuCrearOfertaTemporalActionPerformed(evt);
            }
        });
        menuOperaciones.add(itemMenuCrearOfertaTemporal);

        barraDeMenu.add(menuOperaciones);

        menuReportes.setText("Reportes");

        itemMenuVentasMensual.setText("Reporte ventas mensual");
        itemMenuVentasMensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuVentasMensualActionPerformed(evt);
            }
        });
        menuReportes.add(itemMenuVentasMensual);

        itemMenuVentaPorCategoria.setText("Reportes de venta por categoría");
        itemMenuVentaPorCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuVentaPorCategoriaActionPerformed(evt);
            }
        });
        menuReportes.add(itemMenuVentaPorCategoria);

        itemMenuVentaPorMarca.setText("Reportes de venta por marca");
        itemMenuVentaPorMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuVentaPorMarcaActionPerformed(evt);
            }
        });
        menuReportes.add(itemMenuVentaPorMarca);

        itemMenuEgresoProductos.setText("Egreso de productos por causas especiales");
        itemMenuEgresoProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuEgresoProductosActionPerformed(evt);
            }
        });
        menuReportes.add(itemMenuEgresoProductos);

        itemMenuVariacionPrecios.setText("Variación de precios");
        menuReportes.add(itemMenuVariacionPrecios);

        barraDeMenu.add(menuReportes);

        setJMenuBar(barraDeMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemMenuModificarPrecioPorPorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuModificarPrecioPorPorcentajeActionPerformed
        agregarComponente(new ModificarPrecioUI());
    }//GEN-LAST:event_itemMenuModificarPrecioPorPorcentajeActionPerformed

    private void itemMenuCrearOfertaTemporalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCrearOfertaTemporalActionPerformed
        agregarComponente(new OfertaUI());
    }//GEN-LAST:event_itemMenuCrearOfertaTemporalActionPerformed

    private void itemMenuVentaPorCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuVentaPorCategoriaActionPerformed
        agregarComponente(new VentasPorCategoriaUI());
    }//GEN-LAST:event_itemMenuVentaPorCategoriaActionPerformed

    private void itemMenuVentaPorMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuVentaPorMarcaActionPerformed
        agregarComponente(new VentasPorMarcaUI());
    }//GEN-LAST:event_itemMenuVentaPorMarcaActionPerformed

    private void itemMenuVentasMensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuVentasMensualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemMenuVentasMensualActionPerformed

    private void itemMenuEgresoProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuEgresoProductosActionPerformed
        agregarComponente(new ConsultaEgresosUI());
    }//GEN-LAST:event_itemMenuEgresoProductosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionGerenciaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionGerenciaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionGerenciaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionGerenciaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new GestionGerenciaUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraDeMenu;
    private javax.swing.JMenuItem itemMenuCrearOfertaTemporal;
    private javax.swing.JMenuItem itemMenuEgresoProductos;
    private javax.swing.JMenuItem itemMenuModificarPrecioPorPorcentaje;
    private javax.swing.JMenuItem itemMenuVariacionPrecios;
    private javax.swing.JMenuItem itemMenuVentaPorCategoria;
    private javax.swing.JMenuItem itemMenuVentaPorMarca;
    private javax.swing.JMenuItem itemMenuVentasMensual;
    private javax.swing.JMenu menuOperaciones;
    private javax.swing.JMenu menuReportes;
    // End of variables declaration//GEN-END:variables

    private void agregarComponente(JComponent componente) {
        getContentPane().removeAll();
        add(componente, BorderLayout.CENTER);
        componente.setVisible(true);
        componente.updateUI();
        pack();
    }
}
