package vistas;

import comercio.ControllerSingleton;
import controladoresJPA.RemitoJpaController;
import controladoresJPA.exceptions.CodigoProductoNoRegistradoException;
import modelo.Almacen;
import modelo.Remito;
import vistas.modelos.LotesDelRemitoTableModel;
import java.awt.event.ItemEvent;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Mauro Federico Lopez
 */
public class ImportarUI extends javax.swing.JPanel {

    private RemitoJpaController remitoJpaController;
    private LotesDelRemitoTableModel modeloTabla;

    /**
     * Creates new form ImportarUI
     */
    public ImportarUI() {
        initComponents();
        campoFechaRemito.setValue(new Date());
        remitoJpaController = new RemitoJpaController(ControllerSingleton.getEmf());
        modeloTabla = new LotesDelRemitoTableModel(remitoJpaController);
        tablaLotesDelRemito.setModel(modeloTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nuevoLoteRemitoUI = new javax.swing.JDialog();
        campoCantidad = new javax.swing.JFormattedTextField();
        etiquetaFechaProduccion = new javax.swing.JLabel();
        campoFechaProduccion = new javax.swing.JFormattedTextField();
        etiquetaFechaVencimiento = new javax.swing.JLabel();
        campoCodigoProducto = new javax.swing.JTextField();
        etiquetaCodigoLote = new javax.swing.JLabel();
        campoCodigoLote = new javax.swing.JTextField();
        etiquetaCantidad = new javax.swing.JLabel();
        etiquetaCodigoProducto = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JButton();
        campoFechaVencimiento = new javax.swing.JFormattedTextField();
        botonGuardar = new javax.swing.JButton();
        panelCentral = new javax.swing.JPanel();
        panelDatosDelRemito = new javax.swing.JPanel();
        etiquetaCodigoRemito = new javax.swing.JLabel();
        campoCodigoRemito = new javax.swing.JTextField();
        etiquetaFechaRemito = new javax.swing.JLabel();
        campoFechaRemito = new javax.swing.JFormattedTextField();
        etiquetaSucursalAlmacen = new javax.swing.JLabel();
        campoSucursalAlmacen = new javax.swing.JComboBox();
        panelLotesRemito = new javax.swing.JPanel();
        jsp = new javax.swing.JScrollPane();
        tablaLotesDelRemito = new javax.swing.JTable();
        botonNuevoLoteRemito = new javax.swing.JButton();
        botonEliminarLoteRemito = new javax.swing.JButton();
        panelBotones = new javax.swing.JPanel();
        botonRegistrarOperación = new javax.swing.JButton();
        botonCancelarOperacion = new javax.swing.JButton();

        nuevoLoteRemitoUI.setTitle("Nuevo Lote");
        nuevoLoteRemitoUI.setMinimumSize(new java.awt.Dimension(249, 180));
        nuevoLoteRemitoUI.setResizable(false);

        campoCantidad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        campoCantidad.setToolTipText("");

        etiquetaFechaProduccion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        etiquetaFechaProduccion.setText("Fecha producción");

        campoFechaProduccion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        etiquetaFechaVencimiento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        etiquetaFechaVencimiento.setText("Fecha vencimiento");

        etiquetaCodigoLote.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        etiquetaCodigoLote.setText("Código lote");

        etiquetaCantidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        etiquetaCantidad.setText("Cantidad");

        etiquetaCodigoProducto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        etiquetaCodigoProducto.setText("Código producto");

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        campoFechaVencimiento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nuevoLoteRemitoUILayout = new javax.swing.GroupLayout(nuevoLoteRemitoUI.getContentPane());
        nuevoLoteRemitoUI.getContentPane().setLayout(nuevoLoteRemitoUILayout);
        nuevoLoteRemitoUILayout.setHorizontalGroup(
            nuevoLoteRemitoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevoLoteRemitoUILayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(nuevoLoteRemitoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(nuevoLoteRemitoUILayout.createSequentialGroup()
                        .addGroup(nuevoLoteRemitoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(etiquetaCodigoProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(etiquetaCodigoLote, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(etiquetaCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(nuevoLoteRemitoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoCodigoLote)
                            .addComponent(campoCodigoProducto)
                            .addComponent(campoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(nuevoLoteRemitoUILayout.createSequentialGroup()
                        .addGroup(nuevoLoteRemitoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(etiquetaFechaProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiquetaFechaVencimiento))
                        .addGap(18, 18, 18)
                        .addGroup(nuevoLoteRemitoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoFechaProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nuevoLoteRemitoUILayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonGuardar)
                .addGap(8, 8, 8)
                .addComponent(botonCancelar)
                .addGap(42, 42, 42))
        );
        nuevoLoteRemitoUILayout.setVerticalGroup(
            nuevoLoteRemitoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevoLoteRemitoUILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nuevoLoteRemitoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaCodigoLote)
                    .addComponent(campoCodigoLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nuevoLoteRemitoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaCodigoProducto)
                    .addComponent(campoCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nuevoLoteRemitoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaCantidad)
                    .addComponent(campoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nuevoLoteRemitoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaFechaProduccion)
                    .addComponent(campoFechaProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nuevoLoteRemitoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaFechaVencimiento)
                    .addComponent(campoFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(nuevoLoteRemitoUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGuardar)
                    .addComponent(botonCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Importar Lotes de Productos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        setMaximumSize(new java.awt.Dimension(900, 500));
        setMinimumSize(new java.awt.Dimension(900, 500));
        setPreferredSize(new java.awt.Dimension(900, 500));
        setLayout(new java.awt.BorderLayout());

        panelDatosDelRemito.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del remito", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        panelDatosDelRemito.setMaximumSize(new java.awt.Dimension(900, 100));
        panelDatosDelRemito.setMinimumSize(new java.awt.Dimension(900, 100));
        panelDatosDelRemito.setPreferredSize(new java.awt.Dimension(900, 100));

        etiquetaCodigoRemito.setText("Código remito");

        etiquetaFechaRemito.setText("Fecha remito");

        campoFechaRemito.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        etiquetaSucursalAlmacen.setText("Número de sucursal y de almacén donde se alojarán los lotes");

        campoSucursalAlmacen.setModel(new vistas.modelos.AlmacenComboBoxModel());

        javax.swing.GroupLayout panelDatosDelRemitoLayout = new javax.swing.GroupLayout(panelDatosDelRemito);
        panelDatosDelRemito.setLayout(panelDatosDelRemitoLayout);
        panelDatosDelRemitoLayout.setHorizontalGroup(
            panelDatosDelRemitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosDelRemitoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosDelRemitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etiquetaCodigoRemito, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(etiquetaFechaRemito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosDelRemitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoCodigoRemito, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(campoFechaRemito))
                .addGap(18, 18, 18)
                .addGroup(panelDatosDelRemitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etiquetaSucursalAlmacen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoSucursalAlmacen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(348, Short.MAX_VALUE))
        );
        panelDatosDelRemitoLayout.setVerticalGroup(
            panelDatosDelRemitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosDelRemitoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosDelRemitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaCodigoRemito)
                    .addComponent(campoCodigoRemito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaSucursalAlmacen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosDelRemitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaFechaRemito)
                    .addComponent(campoFechaRemito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoSucursalAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelLotesRemito.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lotes del remito", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        panelLotesRemito.setMaximumSize(new java.awt.Dimension(900, 385));
        panelLotesRemito.setMinimumSize(new java.awt.Dimension(900, 300));
        panelLotesRemito.setPreferredSize(new java.awt.Dimension(900, 385));

        tablaLotesDelRemito.setAutoCreateRowSorter(true);
        tablaLotesDelRemito.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tablaLotesDelRemito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaLotesDelRemito.setColumnSelectionAllowed(true);
        tablaLotesDelRemito.getTableHeader().setReorderingAllowed(false);
        jsp.setViewportView(tablaLotesDelRemito);
        tablaLotesDelRemito.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        botonNuevoLoteRemito.setText("Nuevo");
        botonNuevoLoteRemito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoLoteRemitoActionPerformed(evt);
            }
        });

        botonEliminarLoteRemito.setText("Eliminar");
        botonEliminarLoteRemito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarLoteRemitoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLotesRemitoLayout = new javax.swing.GroupLayout(panelLotesRemito);
        panelLotesRemito.setLayout(panelLotesRemitoLayout);
        panelLotesRemitoLayout.setHorizontalGroup(
            panelLotesRemitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLotesRemitoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLotesRemitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonEliminarLoteRemito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonNuevoLoteRemito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsp, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelLotesRemitoLayout.setVerticalGroup(
            panelLotesRemitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLotesRemitoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLotesRemitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLotesRemitoLayout.createSequentialGroup()
                        .addComponent(botonNuevoLoteRemito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonEliminarLoteRemito))
                    .addComponent(jsp, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelCentralLayout = new javax.swing.GroupLayout(panelCentral);
        panelCentral.setLayout(panelCentralLayout);
        panelCentralLayout.setHorizontalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCentralLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelDatosDelRemito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelLotesRemito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelCentralLayout.setVerticalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
            .addGroup(panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCentralLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelDatosDelRemito, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(panelLotesRemito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        add(panelCentral, java.awt.BorderLayout.CENTER);

        panelBotones.setMaximumSize(new java.awt.Dimension(900, 33));
        panelBotones.setMinimumSize(new java.awt.Dimension(900, 33));
        panelBotones.setPreferredSize(new java.awt.Dimension(900, 33));

        botonRegistrarOperación.setText("Registrar Ingreso de Lotes de Productos");
        botonRegistrarOperación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarOperaciónActionPerformed(evt);
            }
        });
        panelBotones.add(botonRegistrarOperación);

        botonCancelarOperacion.setText("Cancelar Ingreso de Lotes de Productos");
        botonCancelarOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarOperacionActionPerformed(evt);
            }
        });
        panelBotones.add(botonCancelarOperacion);

        add(panelBotones, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarOperaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarOperaciónActionPerformed
        try {
            Remito remito = new Remito();
            remito.setCodigo(campoCodigoRemito.getText());
            remito.setFecha((Date) campoFechaRemito.getValue());
            Almacen almacen = (Almacen) campoSucursalAlmacen.getSelectedItem();
            remitoJpaController.registrarDatosRemito(remito, almacen);
            remitoJpaController.persistirOperacion();
            JOptionPane.showMessageDialog(this, "Se completó la operación con éxito", "Enhorabuena", JOptionPane.INFORMATION_MESSAGE);
        } catch (CodigoProductoNoRegistradoException ex) {
            ex.mostrarDialogo();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonRegistrarOperaciónActionPerformed

    private void botonNuevoLoteRemitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoLoteRemitoActionPerformed
        nuevoLoteRemitoUI.setVisible(true);
        nuevoLoteRemitoUI.pack();
    }//GEN-LAST:event_botonNuevoLoteRemitoActionPerformed

    private void botonEliminarLoteRemitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarLoteRemitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEliminarLoteRemitoActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        try {
            String codigoLote = campoCodigoLote.getText();
            String codigoProducto = campoCodigoProducto.getText();
            Date fechaProduccion = (Date) campoFechaProduccion.getValue();
            Date fechaVencimiento = (Date) campoFechaVencimiento.getValue();
            Double cantidad = ((Number) campoCantidad.getValue()).doubleValue();
            remitoJpaController.agregarLote(codigoLote, codigoProducto, fechaProduccion, fechaVencimiento, cantidad);
            limpiarCampos();
            nuevoLoteRemitoUI.setVisible(false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonCancelarOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarOperacionActionPerformed
        remitoJpaController.cancelarIngresoDeLotesDeProductos();
    }//GEN-LAST:event_botonCancelarOperacionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonCancelarOperacion;
    private javax.swing.JButton botonEliminarLoteRemito;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonNuevoLoteRemito;
    private javax.swing.JButton botonRegistrarOperación;
    private javax.swing.JFormattedTextField campoCantidad;
    private javax.swing.JTextField campoCodigoLote;
    private javax.swing.JTextField campoCodigoProducto;
    private javax.swing.JTextField campoCodigoRemito;
    private javax.swing.JFormattedTextField campoFechaProduccion;
    private javax.swing.JFormattedTextField campoFechaRemito;
    private javax.swing.JFormattedTextField campoFechaVencimiento;
    private javax.swing.JComboBox campoSucursalAlmacen;
    private javax.swing.JLabel etiquetaCantidad;
    private javax.swing.JLabel etiquetaCodigoLote;
    private javax.swing.JLabel etiquetaCodigoProducto;
    private javax.swing.JLabel etiquetaCodigoRemito;
    private javax.swing.JLabel etiquetaFechaProduccion;
    private javax.swing.JLabel etiquetaFechaRemito;
    private javax.swing.JLabel etiquetaFechaVencimiento;
    private javax.swing.JLabel etiquetaSucursalAlmacen;
    private javax.swing.JScrollPane jsp;
    private javax.swing.JDialog nuevoLoteRemitoUI;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelDatosDelRemito;
    private javax.swing.JPanel panelLotesRemito;
    private javax.swing.JTable tablaLotesDelRemito;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {
        campoCodigoLote.setText("");
        campoCodigoProducto.setText("");
        campoCantidad.setValue(0);
        campoFechaProduccion.setValue(null);
        campoFechaVencimiento.setValue(null);
    }

}
