package vistas;

import comercio.ControllerSingleton;
import controladoresJPA.OperacionJpaController;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import modelo.Empleado;
import modelo.Operacion;
import vistas.modelos.MovimientoInventarioTableModel;

/**
 *
 * @author Mauro Federico Lopez
 */
public class RegistroMovimientoInventarioUI extends javax.swing.JPanel {

    private OperacionJpaController operacionJpaController;
    private MovimientoInventarioTableModel modeloTabla;

    /**
     * Creates new form RegistroMovimientoInventarioUI
     */
    public RegistroMovimientoInventarioUI() {
        initComponents();
        modeloTabla = new MovimientoInventarioTableModel();
        jTable1.setModel(modeloTabla);
        operacionJpaController = new OperacionJpaController();
        ArrayList<Operacion> operaciones = operacionJpaController.obtenerOperacionesMovimientoInventario();
        modeloTabla.setOperaciones(operaciones);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        campoEmpleado = new javax.swing.JTextField();
        botonFiltrarPorFecha = new javax.swing.JButton();
        botonFiltrarPorEmpleado = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro de movimiento de inventario", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        setMaximumSize(new java.awt.Dimension(900, 500));
        setMinimumSize(new java.awt.Dimension(900, 500));
        setPreferredSize(new java.awt.Dimension(900, 500));
        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setMaximumSize(new java.awt.Dimension(32767, 390));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(23, 390));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 390));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new MovimientoInventarioTableModel());
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.PAGE_END);

        jLabel1.setText("Filtrar por fecha");

        jLabel2.setText("Filtrar por USERNAME de empleado");

        botonFiltrarPorFecha.setText("Filtrar");
        botonFiltrarPorFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFiltrarPorFechaActionPerformed(evt);
            }
        });

        botonFiltrarPorEmpleado.setText("Filtrar");
        botonFiltrarPorEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFiltrarPorEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(campoEmpleado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonFiltrarPorFecha)
                    .addComponent(botonFiltrarPorEmpleado))
                .addContainerGap(512, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonFiltrarPorFecha)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonFiltrarPorEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void botonFiltrarPorFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFiltrarPorFechaActionPerformed
        Date fecha = jDateChooser1.getDate();
        ArrayList<Operacion> operaciones = operacionJpaController.obtenerOperacionesPorFecha(fecha);
        modeloTabla.setOperaciones(operaciones);
        jDateChooser1.setDate(null);
    }//GEN-LAST:event_botonFiltrarPorFechaActionPerformed

    private void botonFiltrarPorEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFiltrarPorEmpleadoActionPerformed
        try {
            Empleado empleado = ControllerSingleton.getEmpleadoJpaController().obtenerEmpleadoPorUsername(campoEmpleado.getText());
            ArrayList<Operacion> operaciones = operacionJpaController.obtenerOperacionesPorEmpleado(empleado);
            modeloTabla.setOperaciones(operaciones);
            campoEmpleado.setText("");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonFiltrarPorEmpleadoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonFiltrarPorEmpleado;
    private javax.swing.JButton botonFiltrarPorFecha;
    private javax.swing.JTextField campoEmpleado;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
