package vistas;

import comercio.ControllerSingleton;
import controladoresJPA.ProductoJpaController;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import modelo.Categoria;
import modelo.Producto;
import vistas.modelos.VarianzaTableModel;

/**
 *
 * @author Mauro Federico Lopez
 */
public class VariacionPrecioCategoriaUI extends javax.swing.JPanel {

    private ProductoJpaController productoJpaController;
    private VarianzaTableModel modeloTabla;

    /**
     * Creates new form VariacionPrecioCategoriaUI
     */
    public VariacionPrecioCategoriaUI() {
        initComponents();
        productoJpaController = ControllerSingleton.getProductoJpaController();
        modeloTabla = new VarianzaTableModel();
        tablaProductos.setModel(modeloTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDatos = new javax.swing.JPanel();
        campoFechaDesde = new com.toedter.calendar.JDateChooser();
        etiquetaFechaDesde = new javax.swing.JLabel();
        campoFechaHasta = new com.toedter.calendar.JDateChooser();
        etiquetaFechaHasta = new javax.swing.JLabel();
        etiquetaCategoria = new javax.swing.JLabel();
        botonConsutar = new javax.swing.JButton();
        campoCategoria = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Variación de precios de productos de una categoría", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        setMaximumSize(new java.awt.Dimension(900, 500));
        setMinimumSize(new java.awt.Dimension(900, 500));
        setLayout(new java.awt.BorderLayout());

        etiquetaFechaDesde.setText("Periodo desde");

        etiquetaFechaHasta.setText("hasta");

        etiquetaCategoria.setText("Seleccione una categoría");

        botonConsutar.setText("Consultar");
        botonConsutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsutarActionPerformed(evt);
            }
        });

        campoCategoria.setModel(new vistas.modelos.CategoriaComboBoxModel());

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(etiquetaFechaDesde)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoFechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(etiquetaFechaHasta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoFechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(etiquetaCategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonConsutar)))
                .addContainerGap(496, Short.MAX_VALUE))
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campoFechaHasta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaFechaHasta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(campoFechaDesde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(etiquetaFechaDesde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaCategoria)
                    .addComponent(campoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonConsutar))
                .addGap(12, 12, 12))
        );

        add(panelDatos, java.awt.BorderLayout.PAGE_START);

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaProductos);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void botonConsutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsutarActionPerformed
        try {
            Boolean b = (campoFechaDesde.getDate() != null) && (campoFechaHasta.getDate() != null) && (campoCategoria.getSelectedItem() != null);
            if(b) {
                Date desde = campoFechaDesde.getDate();
                Date hasta = campoFechaHasta.getDate();
                Categoria categoria = (Categoria) campoCategoria.getSelectedItem();
                ArrayList<Producto> productos = productoJpaController.obtenerProductosPorCategoria(categoria);
                modeloTabla.actualizarTabla(desde, hasta, productos);
            } else {
                throw new Exception("Campos incompletos.");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonConsutarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConsutar;
    private javax.swing.JComboBox campoCategoria;
    private com.toedter.calendar.JDateChooser campoFechaDesde;
    private com.toedter.calendar.JDateChooser campoFechaHasta;
    private javax.swing.JLabel etiquetaCategoria;
    private javax.swing.JLabel etiquetaFechaDesde;
    private javax.swing.JLabel etiquetaFechaHasta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JTable tablaProductos;
    // End of variables declaration//GEN-END:variables
}
