package comercio.vistas;

import comercio.ControllerSingleton;
import comercio.controladoresJPA.CategoriaJpaController;
import comercio.controladoresJPA.exceptions.NonexistentEntityException;
import comercio.modelo.Categoria;
import comercio.vistas.modelos.CategoriaTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Mauro Federico Lopez
 */
public class AdministrarCategoriasUI extends javax.swing.JPanel {

    private CategoriaJpaController controlador;
    private CategoriaTableModel modeloTabla;

    /**
     * Creates new form AdministrarCategoriasUI
     */
    public AdministrarCategoriasUI() {
        initComponents();
        controlador = ControllerSingleton.getCategoriaJpaController();
        modeloTabla = new CategoriaTableModel();
        tablaCategorias.setModel(modeloTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jsp = new javax.swing.JScrollPane();
        tablaCategorias = new javax.swing.JTable();
        etiquetaNombre = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        etiquetaDescripcion = new javax.swing.JLabel();
        campoDescripcion = new javax.swing.JTextField();
        botonAgregarNuevaCategoria = new javax.swing.JButton();
        botonEliminarCategoria = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(900, 500));
        setMinimumSize(new java.awt.Dimension(900, 500));

        tablaCategorias.setAutoCreateRowSorter(true);
        tablaCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaCategorias.getTableHeader().setReorderingAllowed(false);
        jsp.setViewportView(tablaCategorias);

        etiquetaNombre.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        etiquetaNombre.setText("Nombre");

        etiquetaDescripcion.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        etiquetaDescripcion.setText("Descripción");

        botonAgregarNuevaCategoria.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        botonAgregarNuevaCategoria.setText("Agregar Nueva Categoría");
        botonAgregarNuevaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarNuevaCategoriaActionPerformed(evt);
            }
        });

        botonEliminarCategoria.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        botonEliminarCategoria.setText("Eliminar Categoría");
        botonEliminarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jsp, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiquetaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNombre))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiquetaDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoDescripcion))
                    .addComponent(botonAgregarNuevaCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(botonEliminarCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jsp, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiquetaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiquetaDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(botonAgregarNuevaCategoria)
                        .addGap(7, 7, 7)
                        .addComponent(botonEliminarCategoria)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarNuevaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarNuevaCategoriaActionPerformed
        Categoria nuevaCategoria = new Categoria();
        nuevaCategoria.setNombre(campoNombre.getText());
        nuevaCategoria.setDescripcion(campoDescripcion.getText());
        controlador.create(nuevaCategoria);
        limpiarCampos();
    }//GEN-LAST:event_botonAgregarNuevaCategoriaActionPerformed

    private void botonEliminarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarCategoriaActionPerformed
        Integer rowSelected = tablaCategorias.getSelectedRow();
        if (rowSelected >= 0) {
            try {
                controlador.destroy(modeloTabla.obtenerCategoria(rowSelected).getId());
            } catch (NonexistentEntityException ex) {
                Logger.getLogger(AdministrarCategoriasUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_botonEliminarCategoriaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarNuevaCategoria;
    private javax.swing.JButton botonEliminarCategoria;
    private javax.swing.JTextField campoDescripcion;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JLabel etiquetaDescripcion;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JScrollPane jsp;
    private javax.swing.JTable tablaCategorias;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {
        campoNombre.setText("");
        campoDescripcion.setText("");
    }

}
