package comercio.vistas;

import comercio.ComercioApp;

/**
 *
 * @author Mauro Federico Lopez
 */
public class AdministrarProductosUI extends javax.swing.JPanel {

    /**
     * Creates new form AdministrarProductosUI
     */
    public AdministrarProductosUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jsp = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        botonAgregarNuevoProducto = new javax.swing.JButton();
        botonEliminarProducto = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(900, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Descripcion", "Precio Unitario[$]", "Marca", "Origen", "Descuento[%]", "Unidad", "Categoría"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jsp.setViewportView(tablaProductos);

        add(jsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 11, 800, 450));

        botonAgregarNuevoProducto.setText("Nuevo");
        botonAgregarNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarNuevoProductoActionPerformed(evt);
            }
        });
        add(botonAgregarNuevoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 40));

        botonEliminarProducto.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        botonEliminarProducto.setText("Eliminar");
        add(botonEliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 70, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarNuevoProductoActionPerformed
        new NuevoProductoUI(ComercioApp.getVentanaInventario(), true).setVisible(true);
    }//GEN-LAST:event_botonAgregarNuevoProductoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarNuevoProducto;
    private javax.swing.JButton botonEliminarProducto;
    private javax.swing.JScrollPane jsp;
    private javax.swing.JTable tablaProductos;
    // End of variables declaration//GEN-END:variables
}
