package comercio.vistas;

import comercio.ComercioApp;
import comercio.controladores.ProductosController;
import comercio.exceptions.NonexistentEntityException;
import comercio.modelo.Producto;
import comercio.vistas.modelos.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;

/**
 *
 * @author Mauro Federico Lopez
 */
public class AdministrarProductosUI extends javax.swing.JPanel {

    private ProductosController controlador;

    /**
     * Creates new form AdministrarProductosUI
     */
    public AdministrarProductosUI() {
        initComponents();
        controlador = new ProductosController();

        TableColumn columnaMarca = tablaProductos.getColumnModel().getColumn(3);
        columnaMarca.setCellEditor(new DefaultCellEditor(new JComboBox(new MarcaComboBoxModel())));

        TableColumn columnaOrigen = tablaProductos.getColumnModel().getColumn(4);
        columnaOrigen.setCellEditor(new DefaultCellEditor(new JComboBox(new OrigenComboBoxModel())));

        TableColumn columnaUnidad = tablaProductos.getColumnModel().getColumn(6);
        columnaUnidad.setCellEditor(new DefaultCellEditor(new JComboBox(new UnidadComboBoxModel())));

        TableColumn columnaCategoria = tablaProductos.getColumnModel().getColumn(7);
        columnaCategoria.setCellEditor(new DefaultCellEditor(new JComboBox(new CategoriaComboBoxModel())));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jsp = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        botonAgregarNuevoProducto = new javax.swing.JButton();
        botonEliminarProducto = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(900, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaProductos.setModel(new comercio.vistas.modelos.ProductoTableModel());
        jsp.setViewportView(tablaProductos);

        add(jsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 11, 800, 450));

        botonAgregarNuevoProducto.setText("Nuevo");
        botonAgregarNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarNuevoProductoActionPerformed(evt);
            }
        });
        add(botonAgregarNuevoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 40));

        botonEliminarProducto.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        botonEliminarProducto.setText("Eliminar");
        botonEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarProductoActionPerformed(evt);
            }
        });
        add(botonEliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 70, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarNuevoProductoActionPerformed
        new NuevoProductoUI(ComercioApp.getVentanaInventario(), true).setVisible(true);
    }//GEN-LAST:event_botonAgregarNuevoProductoActionPerformed

    private void botonEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarProductoActionPerformed
        if (tablaProductos.getSelectedRow() >= 0) {
            try {
                controlador.eliminarProducto(((ProductoTableModel) tablaProductos.getModel()).obtenerProducto(tablaProductos.getSelectedRow()));
            } catch (NonexistentEntityException ex) {
                JOptionPane.showMessageDialog(null, "No pudo ser eliminado el producto seleccionado", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No ha seleccionado ningun producto para eliminar", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonEliminarProductoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarNuevoProducto;
    private javax.swing.JButton botonEliminarProducto;
    private javax.swing.JScrollPane jsp;
    private javax.swing.JTable tablaProductos;
    // End of variables declaration//GEN-END:variables
}
