package comercio.vistas;

import java.awt.BorderLayout;
import javax.swing.JComponent;

/**
 *
 * @author Mauro Federico Lopez
 */
public class GestionGerencia extends javax.swing.JFrame {

    /**
     * Creates new form GestionGerencia
     */
    public GestionGerencia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraDeMenu = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        itemMenuReporteVentasMensual = new javax.swing.JMenuItem();
        itemMenuReportesDeVentaPorCategoria = new javax.swing.JMenuItem();
        itemMenuReportesDeVentaPorMarca = new javax.swing.JMenuItem();
        itemMenuProductosProximosAVencer = new javax.swing.JMenuItem();
        menuVer = new javax.swing.JMenu();
        itemMenuModificarPrecioPorPorcentaje = new javax.swing.JMenuItem();
        itemMenuCrearOfertaTemporal = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion Gerencia");
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(950, 550));
        setMinimumSize(new java.awt.Dimension(950, 550));
        setPreferredSize(new java.awt.Dimension(950, 550));
        setResizable(false);

        menuArchivo.setText("Consultas");

        itemMenuReporteVentasMensual.setText("Reporte ventas mensual");
        itemMenuReporteVentasMensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuReporteVentasMensualActionPerformed(evt);
            }
        });
        menuArchivo.add(itemMenuReporteVentasMensual);

        itemMenuReportesDeVentaPorCategoria.setText("Reportes de venta por categoría");
        itemMenuReportesDeVentaPorCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuReportesDeVentaPorCategoriaActionPerformed(evt);
            }
        });
        menuArchivo.add(itemMenuReportesDeVentaPorCategoria);

        itemMenuReportesDeVentaPorMarca.setText("Reportes de venta por marca");
        itemMenuReportesDeVentaPorMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuReportesDeVentaPorMarcaActionPerformed(evt);
            }
        });
        menuArchivo.add(itemMenuReportesDeVentaPorMarca);

        itemMenuProductosProximosAVencer.setText("Productos próximos a vencer");
        itemMenuProductosProximosAVencer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuProductosProximosAVencerActionPerformed(evt);
            }
        });
        menuArchivo.add(itemMenuProductosProximosAVencer);

        barraDeMenu.add(menuArchivo);

        menuVer.setText("Operaciones");

        itemMenuModificarPrecioPorPorcentaje.setText("Modificar precio por porcentaje");
        itemMenuModificarPrecioPorPorcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuModificarPrecioPorPorcentajeActionPerformed(evt);
            }
        });
        menuVer.add(itemMenuModificarPrecioPorPorcentaje);

        itemMenuCrearOfertaTemporal.setText("Crear una oferta temporal");
        itemMenuCrearOfertaTemporal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuCrearOfertaTemporalActionPerformed(evt);
            }
        });
        menuVer.add(itemMenuCrearOfertaTemporal);

        barraDeMenu.add(menuVer);

        setJMenuBar(barraDeMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemMenuModificarPrecioPorPorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuModificarPrecioPorPorcentajeActionPerformed
        agregarComponente(new ModificarPrecioUI());
    }//GEN-LAST:event_itemMenuModificarPrecioPorPorcentajeActionPerformed

    private void itemMenuCrearOfertaTemporalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCrearOfertaTemporalActionPerformed
        agregarComponente(new OfertaUI());
    }//GEN-LAST:event_itemMenuCrearOfertaTemporalActionPerformed

    private void itemMenuReportesDeVentaPorCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuReportesDeVentaPorCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemMenuReportesDeVentaPorCategoriaActionPerformed

    private void itemMenuReportesDeVentaPorMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuReportesDeVentaPorMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemMenuReportesDeVentaPorMarcaActionPerformed

    private void itemMenuReporteVentasMensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuReporteVentasMensualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemMenuReporteVentasMensualActionPerformed

    private void itemMenuProductosProximosAVencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuProductosProximosAVencerActionPerformed
        agregarComponente(new VencimientoProximoUI());
    }//GEN-LAST:event_itemMenuProductosProximosAVencerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new GestionGerencia().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraDeMenu;
    private javax.swing.JMenuItem itemMenuCrearOfertaTemporal;
    private javax.swing.JMenuItem itemMenuModificarPrecioPorPorcentaje;
    private javax.swing.JMenuItem itemMenuProductosProximosAVencer;
    private javax.swing.JMenuItem itemMenuReporteVentasMensual;
    private javax.swing.JMenuItem itemMenuReportesDeVentaPorCategoria;
    private javax.swing.JMenuItem itemMenuReportesDeVentaPorMarca;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuVer;
    // End of variables declaration//GEN-END:variables

    private void agregarComponente(JComponent componente) {
        getContentPane().removeAll();
        add(componente, BorderLayout.CENTER);
        componente.setVisible(true);
        componente.updateUI();
        pack();
    }
}
