package comercio.vistas;

import comercio.ComercioApp;
import comercio.ControllerSingleton;
import comercio.controladores.RemitosController;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Mauro Federico Lopez
 */
public class ImportarUI extends javax.swing.JPanel {

    private RemitosController controlador;

    /**
     * Creates new form ImportarUI
     */
    public ImportarUI() {
        initComponents();
        campoFechaRemito.setValue(new Date());
        controlador = ControllerSingleton.getRemitosController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaTituloFrame = new javax.swing.JLabel();
        botonRegistrarOperación = new javax.swing.JButton();
        panelCentral = new javax.swing.JPanel();
        panelDatosDelRemito = new javax.swing.JPanel();
        etiquetaCodigoRemito = new javax.swing.JLabel();
        campoCodigoRemito = new javax.swing.JTextField();
        etiquetaFechaRemito = new javax.swing.JLabel();
        campoFechaRemito = new javax.swing.JFormattedTextField();
        etiquetaSucursalAlmacen = new javax.swing.JLabel();
        campoSucursalAlmacen = new javax.swing.JComboBox();
        panelLotesRemito = new javax.swing.JPanel();
        jsp = new javax.swing.JScrollPane();
        tablaLotesDelRemito = new javax.swing.JTable();
        botonNuevoLoteRemito = new javax.swing.JButton();
        botonEliminarLoteRemito = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(900, 500));
        setMinimumSize(new java.awt.Dimension(900, 500));
        setLayout(new java.awt.BorderLayout());

        etiquetaTituloFrame.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etiquetaTituloFrame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTituloFrame.setText("Importar Lotes de Productos");
        add(etiquetaTituloFrame, java.awt.BorderLayout.PAGE_START);

        botonRegistrarOperación.setText("Registrar Ingreso de Lotes de Productos");
        botonRegistrarOperación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarOperaciónActionPerformed(evt);
            }
        });
        add(botonRegistrarOperación, java.awt.BorderLayout.PAGE_END);

        panelDatosDelRemito.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del remito", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        panelDatosDelRemito.setMaximumSize(new java.awt.Dimension(900, 100));
        panelDatosDelRemito.setMinimumSize(new java.awt.Dimension(900, 100));
        panelDatosDelRemito.setPreferredSize(new java.awt.Dimension(900, 100));

        etiquetaCodigoRemito.setText("Código remito");

        etiquetaFechaRemito.setText("Fecha remito");

        campoFechaRemito.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        etiquetaSucursalAlmacen.setText("Número de sucursal y de almacén donde se alojarán los lotes");

        campoSucursalAlmacen.setModel(new comercio.vistas.modelos.AlmacenComboBoxModel());

        javax.swing.GroupLayout panelDatosDelRemitoLayout = new javax.swing.GroupLayout(panelDatosDelRemito);
        panelDatosDelRemito.setLayout(panelDatosDelRemitoLayout);
        panelDatosDelRemitoLayout.setHorizontalGroup(
            panelDatosDelRemitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosDelRemitoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosDelRemitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etiquetaCodigoRemito, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(etiquetaFechaRemito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosDelRemitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoCodigoRemito, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(campoFechaRemito))
                .addGap(18, 18, 18)
                .addGroup(panelDatosDelRemitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etiquetaSucursalAlmacen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoSucursalAlmacen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(348, Short.MAX_VALUE))
        );
        panelDatosDelRemitoLayout.setVerticalGroup(
            panelDatosDelRemitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosDelRemitoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosDelRemitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaCodigoRemito)
                    .addComponent(campoCodigoRemito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaSucursalAlmacen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosDelRemitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaFechaRemito)
                    .addComponent(campoFechaRemito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoSucursalAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelLotesRemito.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lotes del remito", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        panelLotesRemito.setMaximumSize(new java.awt.Dimension(900, 385));
        panelLotesRemito.setMinimumSize(new java.awt.Dimension(900, 300));
        panelLotesRemito.setPreferredSize(new java.awt.Dimension(900, 385));

        tablaLotesDelRemito.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tablaLotesDelRemito.setModel(new comercio.vistas.modelos.LoteRemitoTableModel());
        tablaLotesDelRemito.setColumnSelectionAllowed(true);
        tablaLotesDelRemito.getTableHeader().setReorderingAllowed(false);
        jsp.setViewportView(tablaLotesDelRemito);
        tablaLotesDelRemito.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        botonNuevoLoteRemito.setText("Nuevo");
        botonNuevoLoteRemito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoLoteRemitoActionPerformed(evt);
            }
        });

        botonEliminarLoteRemito.setText("Eliminar");
        botonEliminarLoteRemito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarLoteRemitoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLotesRemitoLayout = new javax.swing.GroupLayout(panelLotesRemito);
        panelLotesRemito.setLayout(panelLotesRemitoLayout);
        panelLotesRemitoLayout.setHorizontalGroup(
            panelLotesRemitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLotesRemitoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLotesRemitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonEliminarLoteRemito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonNuevoLoteRemito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsp, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelLotesRemitoLayout.setVerticalGroup(
            panelLotesRemitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLotesRemitoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLotesRemitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLotesRemitoLayout.createSequentialGroup()
                        .addComponent(botonNuevoLoteRemito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonEliminarLoteRemito))
                    .addComponent(jsp, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelCentralLayout = new javax.swing.GroupLayout(panelCentral);
        panelCentral.setLayout(panelCentralLayout);
        panelCentralLayout.setHorizontalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCentralLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelDatosDelRemito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelLotesRemito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelCentralLayout.setVerticalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
            .addGroup(panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCentralLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelDatosDelRemito, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(panelLotesRemito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        add(panelCentral, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarOperaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarOperaciónActionPerformed
        try {
            getControlador().registrarDatosRemito(getCampoCodigoRemito().getText(), getCampoFechaRemito().getValue(), getCampoSucursalAlmacen().getSelectedItem());
            getControlador().persistirOperacion();
            JOptionPane.showMessageDialog(this,
                    "Se completó la operación con éxito",
                    "Enhorabuena",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Algo pasooooo\n" + e,
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonRegistrarOperaciónActionPerformed

    private void botonNuevoLoteRemitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoLoteRemitoActionPerformed
        new NuevoLoteRemitoUI(ComercioApp.getVentanaInventario(),true).setVisible(true);
    }//GEN-LAST:event_botonNuevoLoteRemitoActionPerformed

    private void botonEliminarLoteRemitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarLoteRemitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEliminarLoteRemitoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEliminarLoteRemito;
    private javax.swing.JButton botonNuevoLoteRemito;
    private javax.swing.JButton botonRegistrarOperación;
    private javax.swing.JTextField campoCodigoRemito;
    private javax.swing.JFormattedTextField campoFechaRemito;
    private javax.swing.JComboBox campoSucursalAlmacen;
    private javax.swing.JLabel etiquetaCodigoRemito;
    private javax.swing.JLabel etiquetaFechaRemito;
    private javax.swing.JLabel etiquetaSucursalAlmacen;
    private javax.swing.JLabel etiquetaTituloFrame;
    private javax.swing.JScrollPane jsp;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelDatosDelRemito;
    private javax.swing.JPanel panelLotesRemito;
    private javax.swing.JTable tablaLotesDelRemito;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the controlador
     */
    public RemitosController getControlador() {
        return controlador;
    }

    /**
     * @param controlador the controlador to set
     */
    public void setControlador(RemitosController controlador) {
        this.controlador = controlador;
    }

    /**
     * @return the botonEliminarLoteRemito
     */
    public javax.swing.JButton getBotonEliminarLoteRemito() {
        return botonEliminarLoteRemito;
    }

    /**
     * @param botonEliminarLoteRemito the botonEliminarLoteRemito to set
     */
    public void setBotonEliminarLoteRemito(javax.swing.JButton botonEliminarLoteRemito) {
        this.botonEliminarLoteRemito = botonEliminarLoteRemito;
    }

    /**
     * @return the botonNuevoLoteRemito
     */
    public javax.swing.JButton getBotonNuevoLoteRemito() {
        return botonNuevoLoteRemito;
    }

    /**
     * @param botonNuevoLoteRemito the botonNuevoLoteRemito to set
     */
    public void setBotonNuevoLoteRemito(javax.swing.JButton botonNuevoLoteRemito) {
        this.botonNuevoLoteRemito = botonNuevoLoteRemito;
    }

    /**
     * @return the botonRegistrarOperación
     */
    public javax.swing.JButton getBotonRegistrarOperación() {
        return botonRegistrarOperación;
    }

    /**
     * @param botonRegistrarOperación the botonRegistrarOperación to set
     */
    public void setBotonRegistrarOperación(javax.swing.JButton botonRegistrarOperación) {
        this.botonRegistrarOperación = botonRegistrarOperación;
    }

    /**
     * @return the campoCodigoRemito
     */
    public javax.swing.JTextField getCampoCodigoRemito() {
        return campoCodigoRemito;
    }

    /**
     * @param campoCodigoRemito the campoCodigoRemito to set
     */
    public void setCampoCodigoRemito(javax.swing.JTextField campoCodigoRemito) {
        this.campoCodigoRemito = campoCodigoRemito;
    }

    /**
     * @return the campoFechaRemito
     */
    public javax.swing.JFormattedTextField getCampoFechaRemito() {
        return campoFechaRemito;
    }

    /**
     * @param campoFechaRemito the campoFechaRemito to set
     */
    public void setCampoFechaRemito(javax.swing.JFormattedTextField campoFechaRemito) {
        this.campoFechaRemito = campoFechaRemito;
    }

    /**
     * @return the campoSucursalAlmacen
     */
    public javax.swing.JComboBox getCampoSucursalAlmacen() {
        return campoSucursalAlmacen;
    }

    /**
     * @param campoSucursalAlmacen the campoSucursalAlmacen to set
     */
    public void setCampoSucursalAlmacen(javax.swing.JComboBox campoSucursalAlmacen) {
        this.campoSucursalAlmacen = campoSucursalAlmacen;
    }

    /**
     * @return the etiquetaCodigoRemito
     */
    public javax.swing.JLabel getEtiquetaCodigoRemito() {
        return etiquetaCodigoRemito;
    }

    /**
     * @param etiquetaCodigoRemito the etiquetaCodigoRemito to set
     */
    public void setEtiquetaCodigoRemito(javax.swing.JLabel etiquetaCodigoRemito) {
        this.etiquetaCodigoRemito = etiquetaCodigoRemito;
    }

    /**
     * @return the etiquetaFechaRemito
     */
    public javax.swing.JLabel getEtiquetaFechaRemito() {
        return etiquetaFechaRemito;
    }

    /**
     * @param etiquetaFechaRemito the etiquetaFechaRemito to set
     */
    public void setEtiquetaFechaRemito(javax.swing.JLabel etiquetaFechaRemito) {
        this.etiquetaFechaRemito = etiquetaFechaRemito;
    }

    /**
     * @return the etiquetaSucursalAlmacen
     */
    public javax.swing.JLabel getEtiquetaSucursalAlmacen() {
        return etiquetaSucursalAlmacen;
    }

    /**
     * @param etiquetaSucursalAlmacen the etiquetaSucursalAlmacen to set
     */
    public void setEtiquetaSucursalAlmacen(javax.swing.JLabel etiquetaSucursalAlmacen) {
        this.etiquetaSucursalAlmacen = etiquetaSucursalAlmacen;
    }

    /**
     * @return the etiquetaTituloFrame
     */
    public javax.swing.JLabel getEtiquetaTituloFrame() {
        return etiquetaTituloFrame;
    }

    /**
     * @param etiquetaTituloFrame the etiquetaTituloFrame to set
     */
    public void setEtiquetaTituloFrame(javax.swing.JLabel etiquetaTituloFrame) {
        this.etiquetaTituloFrame = etiquetaTituloFrame;
    }

    /**
     * @return the jsp
     */
    public javax.swing.JScrollPane getJsp() {
        return jsp;
    }

    /**
     * @param jsp the jsp to set
     */
    public void setJsp(javax.swing.JScrollPane jsp) {
        this.jsp = jsp;
    }

    /**
     * @return the panelCentral
     */
    public javax.swing.JPanel getPanelCentral() {
        return panelCentral;
    }

    /**
     * @param panelCentral the panelCentral to set
     */
    public void setPanelCentral(javax.swing.JPanel panelCentral) {
        this.panelCentral = panelCentral;
    }

    /**
     * @return the panelDatosDelRemito
     */
    public javax.swing.JPanel getPanelDatosDelRemito() {
        return panelDatosDelRemito;
    }

    /**
     * @param panelDatosDelRemito the panelDatosDelRemito to set
     */
    public void setPanelDatosDelRemito(javax.swing.JPanel panelDatosDelRemito) {
        this.panelDatosDelRemito = panelDatosDelRemito;
    }

    /**
     * @return the panelLotesRemito
     */
    public javax.swing.JPanel getPanelLotesRemito() {
        return panelLotesRemito;
    }

    /**
     * @param panelLotesRemito the panelLotesRemito to set
     */
    public void setPanelLotesRemito(javax.swing.JPanel panelLotesRemito) {
        this.panelLotesRemito = panelLotesRemito;
    }

    /**
     * @return the tablaLotesDelRemito
     */
    public javax.swing.JTable getTablaLotesDelRemito() {
        return tablaLotesDelRemito;
    }

    /**
     * @param tablaLotesDelRemito the tablaLotesDelRemito to set
     */
    public void setTablaLotesDelRemito(javax.swing.JTable tablaLotesDelRemito) {
        this.tablaLotesDelRemito = tablaLotesDelRemito;
    }
}
