package comercio.vistas;

import comercio.ComercioApp;
import comercio.controladoresJPA.OfertaJpaController;
import comercio.controladoresJPA.exceptions.CampoIncompletoException;
import comercio.modelo.Categoria;
import comercio.modelo.Marca;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mauro Federico Lopez
 */
public class OfertaUI extends javax.swing.JPanel {

    private OfertaJpaController ofertaJpaController;

    /**
     * Creates new form OfertaUI
     */
    public OfertaUI() {
        initComponents();
        ofertaJpaController = new OfertaJpaController(ComercioApp.getEntityManagerFactory());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelOfertaProducto = new javax.swing.JPanel();
        etiquetaCodigoProducto = new javax.swing.JLabel();
        etiquetaPorcentajeDescuentoProducto = new javax.swing.JLabel();
        campoPorcentajeDescuentoProducto = new javax.swing.JFormattedTextField();
        etiquetaFechaInicioProducto = new javax.swing.JLabel();
        campoFechaInicioProducto = new javax.swing.JFormattedTextField();
        etiquetaFechaFinProducto = new javax.swing.JLabel();
        campoFechaFinProducto = new javax.swing.JFormattedTextField();
        botonCrearOfertaProducto = new javax.swing.JButton();
        campoCodigoProducto = new javax.swing.JTextField();
        panelOfertaCategoria = new javax.swing.JPanel();
        etiquetaCategoria = new javax.swing.JLabel();
        campoCategoria = new javax.swing.JComboBox();
        etiquetaPorcentajeDescuentoCategoria = new javax.swing.JLabel();
        campoPorcentajeDescuentoCategoria = new javax.swing.JFormattedTextField();
        etiquetaFechaInicioCategoria = new javax.swing.JLabel();
        campoFechaInicioCategoria = new javax.swing.JFormattedTextField();
        etiquetaFechaFinCategoria = new javax.swing.JLabel();
        campoFechaFinCategoria = new javax.swing.JFormattedTextField();
        botonCrearOfertaCategoria = new javax.swing.JButton();
        panelOfertaMarca = new javax.swing.JPanel();
        etiquetaMarca = new javax.swing.JLabel();
        campoMarca = new javax.swing.JComboBox();
        etiquetaPorcentajeDescuentoMarca = new javax.swing.JLabel();
        campoPorcentajeDescuentoMarca = new javax.swing.JFormattedTextField();
        etiquetaFechaInicioMarca = new javax.swing.JLabel();
        campoFechaInicioMarca = new javax.swing.JFormattedTextField();
        etiquetaFechaFinMarca = new javax.swing.JLabel();
        campoFechaFinMarca = new javax.swing.JFormattedTextField();
        botonCrearOfertaMarca = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(900, 500));
        setMinimumSize(new java.awt.Dimension(900, 500));
        setLayout(new java.awt.BorderLayout());

        panelOfertaProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Crear oferta para un producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        panelOfertaProducto.setMaximumSize(new java.awt.Dimension(900, 160));
        panelOfertaProducto.setMinimumSize(new java.awt.Dimension(900, 160));
        panelOfertaProducto.setPreferredSize(new java.awt.Dimension(900, 160));

        etiquetaCodigoProducto.setText("Ingrese el código del producto");

        etiquetaPorcentajeDescuentoProducto.setText("Indique el porcentaje de descuento");

        campoPorcentajeDescuentoProducto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00%"))));

        etiquetaFechaInicioProducto.setText("Indique la fecha de inicio de la oferta");

        campoFechaInicioProducto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        etiquetaFechaFinProducto.setText("Indique la fecha de fin de la oferta");

        campoFechaFinProducto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        botonCrearOfertaProducto.setText("Crear Oferta");
        botonCrearOfertaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearOfertaProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOfertaProductoLayout = new javax.swing.GroupLayout(panelOfertaProducto);
        panelOfertaProducto.setLayout(panelOfertaProductoLayout);
        panelOfertaProductoLayout.setHorizontalGroup(
            panelOfertaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOfertaProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOfertaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(etiquetaFechaFinProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaFechaInicioProducto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaPorcentajeDescuentoProducto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaCodigoProducto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOfertaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoPorcentajeDescuentoProducto)
                    .addComponent(campoFechaInicioProducto)
                    .addComponent(campoFechaFinProducto)
                    .addComponent(botonCrearOfertaProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(campoCodigoProducto))
                .addContainerGap(533, Short.MAX_VALUE))
        );
        panelOfertaProductoLayout.setVerticalGroup(
            panelOfertaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOfertaProductoLayout.createSequentialGroup()
                .addGroup(panelOfertaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaCodigoProducto)
                    .addComponent(campoCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOfertaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoPorcentajeDescuentoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaPorcentajeDescuentoProducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOfertaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoFechaInicioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaFechaInicioProducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOfertaProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoFechaFinProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaFechaFinProducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCrearOfertaProducto)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        add(panelOfertaProducto, java.awt.BorderLayout.PAGE_START);

        panelOfertaCategoria.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Crear oferta para los productos de una categoría", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        panelOfertaCategoria.setMaximumSize(new java.awt.Dimension(900, 160));
        panelOfertaCategoria.setMinimumSize(new java.awt.Dimension(900, 160));
        panelOfertaCategoria.setPreferredSize(new java.awt.Dimension(900, 160));

        etiquetaCategoria.setText("Seleccione una categoría");

        campoCategoria.setModel(new comercio.vistas.modelos.CategoriaComboBoxModel());

        etiquetaPorcentajeDescuentoCategoria.setText("Indique el porcentaje de descuento");

        campoPorcentajeDescuentoCategoria.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getPercentInstance())));

        etiquetaFechaInicioCategoria.setText("Indique la fecha de inicio de la oferta");

        campoFechaInicioCategoria.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        etiquetaFechaFinCategoria.setText("Indique la fecha de fin de la oferta");

        campoFechaFinCategoria.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        botonCrearOfertaCategoria.setText("Crear Oferta");
        botonCrearOfertaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearOfertaCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOfertaCategoriaLayout = new javax.swing.GroupLayout(panelOfertaCategoria);
        panelOfertaCategoria.setLayout(panelOfertaCategoriaLayout);
        panelOfertaCategoriaLayout.setHorizontalGroup(
            panelOfertaCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOfertaCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOfertaCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(etiquetaFechaFinCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaFechaInicioCategoria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaPorcentajeDescuentoCategoria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaCategoria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOfertaCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoPorcentajeDescuentoCategoria)
                    .addComponent(campoFechaInicioCategoria)
                    .addComponent(campoFechaFinCategoria)
                    .addComponent(botonCrearOfertaCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(533, Short.MAX_VALUE))
        );
        panelOfertaCategoriaLayout.setVerticalGroup(
            panelOfertaCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOfertaCategoriaLayout.createSequentialGroup()
                .addGroup(panelOfertaCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaCategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOfertaCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoPorcentajeDescuentoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaPorcentajeDescuentoCategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOfertaCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoFechaInicioCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaFechaInicioCategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOfertaCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoFechaFinCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaFechaFinCategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCrearOfertaCategoria)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        add(panelOfertaCategoria, java.awt.BorderLayout.CENTER);

        panelOfertaMarca.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Crear oferta para los productos de una marca", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        panelOfertaMarca.setMaximumSize(new java.awt.Dimension(900, 160));
        panelOfertaMarca.setMinimumSize(new java.awt.Dimension(900, 160));
        panelOfertaMarca.setPreferredSize(new java.awt.Dimension(900, 160));

        etiquetaMarca.setText("Seleccione una marca");

        campoMarca.setModel(new comercio.vistas.modelos.CategoriaComboBoxModel());

        etiquetaPorcentajeDescuentoMarca.setText("Indique el porcentaje de descuento");

        campoPorcentajeDescuentoMarca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getPercentInstance())));

        etiquetaFechaInicioMarca.setText("Indique la fecha de inicio de la oferta");

        campoFechaInicioMarca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        etiquetaFechaFinMarca.setText("Indique la fecha de fin de la oferta");

        campoFechaFinMarca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        botonCrearOfertaMarca.setText("Crear Oferta");
        botonCrearOfertaMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearOfertaMarcaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOfertaMarcaLayout = new javax.swing.GroupLayout(panelOfertaMarca);
        panelOfertaMarca.setLayout(panelOfertaMarcaLayout);
        panelOfertaMarcaLayout.setHorizontalGroup(
            panelOfertaMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOfertaMarcaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOfertaMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(etiquetaFechaFinMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaFechaInicioMarca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaPorcentajeDescuentoMarca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaMarca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOfertaMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoMarca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoPorcentajeDescuentoMarca)
                    .addComponent(campoFechaInicioMarca)
                    .addComponent(campoFechaFinMarca)
                    .addComponent(botonCrearOfertaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(533, Short.MAX_VALUE))
        );
        panelOfertaMarcaLayout.setVerticalGroup(
            panelOfertaMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOfertaMarcaLayout.createSequentialGroup()
                .addGroup(panelOfertaMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaMarca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOfertaMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoPorcentajeDescuentoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaPorcentajeDescuentoMarca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOfertaMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoFechaInicioMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaFechaInicioMarca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOfertaMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoFechaFinMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaFechaFinMarca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCrearOfertaMarca)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        add(panelOfertaMarca, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void botonCrearOfertaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearOfertaProductoActionPerformed
        try {
            camposOfertaProductoCompletos();
            String codigoProducto = campoCodigoProducto.getText();
            Double descuento = ((Number) campoPorcentajeDescuentoProducto.getValue()).doubleValue();
            Date fechaInicio = (Date) campoFechaInicioProducto.getValue();
            Date fechaFin = (Date) campoFechaFinProducto.getValue();
            ofertaJpaController.crearOfertaParaProducto(codigoProducto, descuento, fechaInicio, fechaFin);
            campoCodigoProducto.setText("");
            campoPorcentajeDescuentoProducto.setValue(null);
            campoFechaInicioProducto.setValue(null);
            campoFechaFinProducto.setValue(null);
            JOptionPane.showMessageDialog(null, "Se ha completó la operación.", "Enhorabuena", JOptionPane.INFORMATION_MESSAGE);
        } catch(CampoIncompletoException ex) {
            ex.mostrarDialogo();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonCrearOfertaProductoActionPerformed

    private void botonCrearOfertaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearOfertaCategoriaActionPerformed
        try {
            Categoria categoria = (Categoria) campoCategoria.getSelectedItem();
            Double descuento = ((Number) campoPorcentajeDescuentoCategoria.getValue()).doubleValue();
            Date fechaInicio = (Date) campoFechaInicioCategoria.getValue();
            Date fechaFin = (Date) campoFechaFinCategoria.getValue();
            ofertaJpaController.crearOfertaParaProductosDeUnaCategoria(categoria, descuento, fechaInicio, fechaFin);
            campoCategoria.setSelectedItem(null);
            campoPorcentajeDescuentoCategoria.setValue(null);
            campoFechaInicioCategoria.setValue(null);
            campoFechaFinCategoria.setValue(null);
            JOptionPane.showMessageDialog(null, "Se ha completó la operación.", "Enhorabuena", JOptionPane.INFORMATION_MESSAGE);
        } catch(CampoIncompletoException ex) {
            ex.mostrarDialogo();
        } catch (Exception ex) {
            Logger.getLogger(OfertaUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonCrearOfertaCategoriaActionPerformed

    private void botonCrearOfertaMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearOfertaMarcaActionPerformed
        try {
            Marca marca = (Marca) campoMarca.getSelectedItem();
            Double descuento = ((Number) campoPorcentajeDescuentoMarca.getValue()).doubleValue();
            Date fechaInicio = (Date) campoFechaInicioMarca.getValue();
            Date fechaFin = (Date) campoFechaFinMarca.getValue();
            ofertaJpaController.crearOfertaParaProductosDeUnaMarca(marca, descuento, fechaInicio, fechaFin);
            campoCategoria.setSelectedItem(null);
            campoPorcentajeDescuentoMarca.setValue(null);
            campoFechaInicioMarca.setValue(null);
            campoFechaFinMarca.setValue(null);
            JOptionPane.showMessageDialog(null, "Se ha completó la operación.", "Enhorabuena", JOptionPane.INFORMATION_MESSAGE);
        } catch(CampoIncompletoException ex) {
            ex.mostrarDialogo();
        } catch (Exception ex) {
            Logger.getLogger(OfertaUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonCrearOfertaMarcaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrearOfertaCategoria;
    private javax.swing.JButton botonCrearOfertaMarca;
    private javax.swing.JButton botonCrearOfertaProducto;
    private javax.swing.JComboBox campoCategoria;
    private javax.swing.JTextField campoCodigoProducto;
    private javax.swing.JFormattedTextField campoFechaFinCategoria;
    private javax.swing.JFormattedTextField campoFechaFinMarca;
    private javax.swing.JFormattedTextField campoFechaFinProducto;
    private javax.swing.JFormattedTextField campoFechaInicioCategoria;
    private javax.swing.JFormattedTextField campoFechaInicioMarca;
    private javax.swing.JFormattedTextField campoFechaInicioProducto;
    private javax.swing.JComboBox campoMarca;
    private javax.swing.JFormattedTextField campoPorcentajeDescuentoCategoria;
    private javax.swing.JFormattedTextField campoPorcentajeDescuentoMarca;
    private javax.swing.JFormattedTextField campoPorcentajeDescuentoProducto;
    private javax.swing.JLabel etiquetaCategoria;
    private javax.swing.JLabel etiquetaCodigoProducto;
    private javax.swing.JLabel etiquetaFechaFinCategoria;
    private javax.swing.JLabel etiquetaFechaFinMarca;
    private javax.swing.JLabel etiquetaFechaFinProducto;
    private javax.swing.JLabel etiquetaFechaInicioCategoria;
    private javax.swing.JLabel etiquetaFechaInicioMarca;
    private javax.swing.JLabel etiquetaFechaInicioProducto;
    private javax.swing.JLabel etiquetaMarca;
    private javax.swing.JLabel etiquetaPorcentajeDescuentoCategoria;
    private javax.swing.JLabel etiquetaPorcentajeDescuentoMarca;
    private javax.swing.JLabel etiquetaPorcentajeDescuentoProducto;
    private javax.swing.JPanel panelOfertaCategoria;
    private javax.swing.JPanel panelOfertaMarca;
    private javax.swing.JPanel panelOfertaProducto;
    // End of variables declaration//GEN-END:variables

    private void camposOfertaProductoCompletos() throws CampoIncompletoException {
        if(campoCodigoProducto.getText().isEmpty())
            throw new CampoIncompletoException("No ha indicado el código del producto.");
        if(campoPorcentajeDescuentoProducto.getValue() == null)
            throw new CampoIncompletoException("No ha indicado el porcentaje de descuento.");
        if(campoFechaInicioProducto.getValue() == null)
            throw new CampoIncompletoException("No ha indicado la fecha de inicio de la oferta.");
        if(campoFechaFinProducto.getValue() == null)
            throw new CampoIncompletoException("No ha indicado la fecha de fin de la oferta.");
    }

    private void camposOfertaCategoriaCompletos() throws CampoIncompletoException {
        if(campoCategoria.getSelectedItem() == null)
            throw new CampoIncompletoException("No ha seleccionado una categoría.");
        if(campoPorcentajeDescuentoCategoria.getValue() == null)
            throw new CampoIncompletoException("No ha indicado el porcentaje de descuento.");
        if(campoFechaInicioCategoria.getValue() == null)
            throw new CampoIncompletoException("No ha indicado la fecha de inicio de la oferta.");
        if(campoFechaFinCategoria.getValue() == null)
            throw new CampoIncompletoException("No ha indicado la fecha de fin de la oferta.");
    }

    private void camposOfertaMarcaCompletos() throws CampoIncompletoException {
        if(campoMarca.getSelectedItem() == null)
            throw new CampoIncompletoException("No ha seleccionado una marca.");
        if(campoPorcentajeDescuentoMarca.getValue() == null)
            throw new CampoIncompletoException("No ha indicado el porcentaje de descuento.");
        if(campoFechaInicioMarca.getValue() == null)
            throw new CampoIncompletoException("No ha indicado la fecha de inicio de la oferta.");
        if(campoFechaFinMarca.getValue() == null)
            throw new CampoIncompletoException("No ha indicado la fecha de fin de la oferta.");
    }

}
