package comercio;

import com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException;
import comercio.controladoresJPA.UnidadJpaController;
import comercio.modelo.Unidad;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.RollbackException;
import javax.swing.JOptionPane;

/**
 *
 * @author Mauro
 */
public class Testings extends javax.swing.JFrame {

    private EntityManagerFactory emf;
    private UnidadJpaController unidadJpaController;

    /**
     * Creates new form Testings
     */
    public Testings() {
        initComponents();
        emf = Persistence.createEntityManagerFactory("ComercioPU");
        unidadJpaController = new UnidadJpaController(emf);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiqueta = new javax.swing.JLabel();
        campo = new javax.swing.JTextField();
        boton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(478, 70));
        setPreferredSize(new java.awt.Dimension(478, 70));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        etiqueta.setText("Nombre de la unidad");
        getContentPane().add(etiqueta, java.awt.BorderLayout.LINE_START);

        campo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoKeyPressed(evt);
            }
        });
        getContentPane().add(campo, java.awt.BorderLayout.CENTER);

        boton.setText("Guardar");
        boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActionPerformed(evt);
            }
        });
        getContentPane().add(boton, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActionPerformed
        accionDelBoton();
    }//GEN-LAST:event_botonActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            accionDelBoton();
        }
    }//GEN-LAST:event_formKeyPressed

    private void campoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoKeyPressed
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            accionDelBoton();
        }
    }//GEN-LAST:event_campoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Testings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                Testings testings = new Testings();
                testings.setVisible(true);
                testings.pack();
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton;
    private javax.swing.JTextField campo;
    private javax.swing.JLabel etiqueta;
    // End of variables declaration//GEN-END:variables

    public void accionDelBoton() {
        try {
            Unidad unidad = new Unidad();
            unidad.setDescripcion(campo.getText());
            unidadJpaController.create(unidad);
        } catch (RollbackException e) {
            Throwable t = e.getCause().getCause();
            if(t.getClass() == com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException.class) {
                MySQLIntegrityConstraintViolationException constraintViolationException = (MySQLIntegrityConstraintViolationException) t;
                JOptionPane.showMessageDialog(null, constraintViolationException.getLocalizedMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

}
